## Vérification (copie, suppréssion, déplacement de fichiers)

In [57]:
import os
import numpy as np
import shutil
from tqdm import tqdm

# rename

root = '../outputs/pseudo-earl/nantes/'

for subject in tqdm(os.listdir(root), position=0, desc='Renaming files', leave=True):
    subject_folder = os.path.join(root, subject)
    if os.path.isdir(subject_folder):
        for voi in os.listdir(subject_folder):
            voi_folder = os.path.join(subject_folder, voi)
            for file in os.listdir(voi_folder):
                m, n = 'earl_0', 'earl1'
                if m in file:
                    old_file_path = os.path.join(voi_folder, file)
                    new_file_name = file.replace(m, n)
                    new_file_path = os.path.join(voi_folder, new_file_name)
                    shutil.move(old_file_path, new_file_path)

Renaming files: 100%|██████████| 89/89 [00:00<00:00, 2720.79it/s]

In [17]:
import os
import numpy as np
import shutil
from tqdm import tqdm

# delete all csv files

root = '../outputs/pseudo-earl/nantes/'

for subject in tqdm(os.listdir(root), position=0, desc='Deleting files', leave=True):
    subject_folder = os.path.join(root, subject)
    if os.path.isdir(subject_folder):
        for voi in os.listdir(subject_folder):
            voi_folder = os.path.join(subject_folder, voi)
            for file in os.listdir(voi_folder):
                if file.endswith('.csv'):
                    file_path = os.path.join(voi_folder, file)
                    os.remove(file_path)

Deleting files: 100%|██████████| 89/89 [00:00<00:00, 3481.50it/s]

In [ ]:
root = 'data/PET-EARL/foundation-dataset/domain_rennes/'

# count number of files starting with predicted_EARL* in each subject folder (return int for each subject)
# display subjects with > 1
for subject in tqdm(os.listdir(root), position=0, desc='Counting files', leave=True):
    subject_folder = os.path.join(root, subject)
    if os.path.isdir(subject_folder):
        count = 0
        for file in os.listdir(subject_folder):
            if file.startswith('predicted_EARL'):
                count += 1
        if count > 1:
            print(f'Subject {subject} has {count} files starting with predicted_EARL')

In [122]:
import numpy as np
from tqdm import tqdm
import os

rng = np.random.default_rng(seed=101)

root = 'data/PET-EARL/foundation-dataset/domain_rennes/'


# how much subjects contain file "predicted_EARL1_DSR10" and save subject ids in a list
count, subjects = 0, list()
for subject in tqdm(sorted(os.listdir(root)), position=0, desc='Counting subjects', leave=True):
    subject_folder = os.path.join(root, subject)
    if os.path.isdir(subject_folder):
        for file in os.listdir(subject_folder):
            if file.startswith('CT'):
                subjects.append(subject)
                count += 1
                break

# select 50 random subjects
# selected_subjects = rng.choice(subjects, size=50, replace=False)
            
print(f'Number of subjects: {count}')

Counting subjects: 100%|██████████| 75/75 [00:00<00:00, 16003.91it/s]

Number of subjects: 75

In [16]:
evaluation_subject_ids = {
    'domain_a100': [
        'A100792537', 'A100738988', 'A100764406', 'A100765582', 'A100792517', 'A100789833', 'A100680483', 'A100738804', 'A100560539', 'A100784916',
        'A100761203', 'A100794227', 'A100759366', 'A100784481', 'A100721721', 'A100778064', 'A100672908', 'A100793026', 'A100783219', 'A100681810',
        'A100730682', 'A100740690', 'A100739271', 'A100678049', 'A100792727', 'A100786953', 'A100767881', 'A100707355', 'A100738911', 'A100783842',
        'A100737608', 'A100720493', 'A100738767', 'A100668903', 'A100780748', 'A100783275', 'A100748980', 'A100780240', 'A100730959', 'A100739006',
        'A100782126', 'A100748174', 'A100786185', 'A100743451', 'A100750063', 'A100778778', 'A100779499', 'A100751077', 'A100785598', 'A100792034'
    ],
    'domain_rennes': [
        '2KxS5KpUTLWh3qiQiyPs8J', '2eLoHvwtUjSnYAHKYDWuzw', '2saGpAnVAUrRMZ9Mhyz95T', '2ybL92aNCnoQcHxamqh4r8', '3ePZxLszjdLzWWfvrzxQND',
        '3yPTnAs4wZmYDjsY9tvepb', '43fgogUgwCvLkkbmfHkxBX', '4V5Yz3ocu6CcwuhVq38LSR', '4bYLrdGX6Zj569sVydX5uy', '4jJhJSHeiiXLmftGbGHxhS', 
        '4jzaeDGxuPX4fCfUvDbQuj', '5s8ZTzvhDkSBZ9vJ3vTAhg', '6FUnHSKr2rztBpzNEUvMg4', '6fqzQDyXnAxwWmt7Cg3Yom', '7DaBpjcJPAEBCMhmFpgb5j', 
        '7uK9RmAChXtqziY7pW5Dsa', '8aBN55PCdErWthtc3Y6K9T', '9MkG9YCPJqjcTNoGMyqZh5', '9MzDqX7RRioqo9rvf9THcD', 'ArTMw7c7PQ3zhtpaS4M8fk', 
        'CycDYjZVUXgW5ukQUW4TC7', 'DwPmeDoXZYWJZZ4e2qmRPx', 'Eoozgda4UVszGUcVmMN3qr', 'FLSCiLeVxA2fwYnzEfctyU', 'FhjK3fuwuNZ8cb2CQC76DV', 
        'FqEf7mTqYKrB83vGk6xqQS', 'G38MAFQ8QJxmP3RdDgtatM', 'GPF7DHQtL7BknnYja84RsS', 'GQz9nY6LSG2GNcbDnPWWsi', 'GpMghx6KCQmcY7c3TS9nEn', 
        'HNxD4294tCwor8Q279PadP', 'HPdK8qEKMH2jmTk6bGFhTT', 'Jssbv8wnaAUMY9BAzkzFLr', 'KJxTNtbpCqxZgfKFkLL5bw', 'KLhQwpbbFaL7t7zLhrHk6p', 
        'LH2rQD9ib4KZ5GRSE8AP6q', 'LazJcKFPHizr55EtCj4dDF', 'Mdr4hC9a6ceoQzYFGMWhm9', 'Nrfs8M7unx7fcaSJECYBC3', 'P3CMSYQHbUzsxCqF6naxWq', 
        'Piph5SiyBhRTMvGS6WNkKD', 'QCUUZfRhj7hnniiVkAXs6B', 'SN88PUgr36xHCc9R3HgKNC', 'SYPxsGPFytXdPHmmVxBPDo', 'T3Ma8JKQtBT4LPus4Jxeh3', 
        'TE2swsiFL9BckDDwje5BEm', 'UXKrHrDKshLbyyHd2G5mVp', 'VjghsnARRYj63muf5NYjBv', 'VmYX8qGn8EKjdhvLMsJrs7', 'W3G7QPSz9zYCKTi7W6svV5', 
        'W7r3YvDijSJssBRqfPzaCG', 'WNpLDJcE8kaQt6YXSVcvbw', 'X8mcdRzrMuzzpfYAMxzozt', 'Xi7jfGu7M4LpcE2vkoGCKf', 'XiVyPLpRQgWLfHY8Wkpw3N', 
        'Y89iNoWEoRWohbsz5B3vWH', 'YeE6xB28d2U6kn86m2JiBU', 'ZBVNS2t2iZH7wcepE8F4YS', 'ZBknjLXpYrRkTVD6uoC8Cz', 'Zj8fVmNfYeAtJnr93L538V', 
        'Zp6n3YLNQfdVr8s4qPvs5D', 'aDcCdL2rRSXNSDBc8gbas7', 'eATSittkopiQUBHr4bMvhV', 'ehA9bCaqVajEGu9tPzvnjb', 'fMi45AwSLcvi5c7WDud2JG', 
        'fPjppHbFyhZBsDQGbLVwRh', 'gLBBcHJhNu6YktJxCpRokL', 'gw2kfxahaHTjAK5kzPLmmu', 'ioPAP7D9tR3C8G4KfVKhA3', 'knaDEJdkT7Fyit7Jv83aiX', 
        'komWetdTp2nRXqeLvDaAgv', 'mw8KJNCixqMhCvxDhrqmt2', 'n5nHWAtDTxGHejhyMvaDgT', 'nWhT5ggKSQKZaiahmEiBho', 'nb7SQMC5vKR3wLBjCmobt7'
    ],
    'domain_chb': [
        '9401183706m', '9401155949m', '9401169957m', '9401163865m', '9401178648m', '9401161671m', '9401189196m', '9401181171m', '9401167762m', 
        '9401162244m', '9401180152m', '9401179707m', '9401160981m', '9401181665m', '9401163861m', '9401186758m', '9401176393m', '9401164473m', 
        '9401166814m', '9401174186m', '9401181672m', '9401188271m', '9401172523m', '9401173362m', '9401162547m', '9401162558m', '9401157388m', 
        '9401174166m', '9401185604m', '9401170633m', '9401154316m', '9401166817m', '9401174662m', '9401170647m', '9401169545m', '9401177214m', 
        '9401170709m', '9401169832m', '9401183962m', '9401171128m', '9401165833m', '9401181688m', '9401165200m', '9401167764m', '9401157261m', 
        '9401152852m', '9401174635m', '9401165575m', '9401155238m', '9401157266m', '9401183703m', '9401154473m', '9401165356m', '9401172518m', 
        '9401160865m', '9401182180m', '9401161699m', '9401183379m', '9401178641m', '9401172121m', '9401186262m', '9401168285m', '9401175514m', 
        '9401158785m', '9401155800m', '9401162548m', '9401187711m', '9401178639m', '9401176815m', '9401162139m', '9401170653m', '9401173764m', 
        '9401167795m', '9401186257m', '9401162954m', '9401157267m', '9401183712m', '9401166800m', '9401176821m', '9401163399m', '9401178638m', 
        '9401180145m', '9401185783m', '9401178644m', '9401158782m', '9401176812m', '9401171878m', '9401154314m', '9401187184m', '9401176380m', 
        '9401190122m', '9401165330m', '9401160877m', '9401175631m', '9401166363m', '9401182654m', '9401162130m', '9401173372m', '9401182647m', 
        '9401167765m'
    ],
    'domain_nantes': [
        '03240000', '06370000', '07130000', '07270000', '07500000', '08500000', '09360000', '10200000', '10220000', '10530000', '11060000', 
        '11240000', '11330000', '11390000', '11590000', '12260000', '12320000', '12400000', '13160000', '13250000', '13340000', '13400000', 
        '14050000', '14180000', '14250000', '14330000', '15070000', '15080000', '15160000', '15240000', '15560000', '16070000', '16270000', 
        '16300000', '16570000', '16574000', '17230000', '18100000', '18500000', '19030000', '19140000', '19440000', '19510000', 
        '20310000', '20510000', '21010000', '21310000', '21560000', '22220000', '22550000', '23250000', '23280000', '24200000', '24240000', 
        '25080000', '25180000', '25380000', '26080000', '26370000', '27080000', '27380000', '28140000', '28460000', '29170000', '29480000', 
        '30200000', '30490000', '31170000', '31450000', '32150000', '32460000', '39030000', '40360000', '41430000', '42350000', '43300000', 
        '44280000', '45250000', '46210000', '48110000', '49100000', '50370000', '51350000', '52290000', '53300000', '54370000', '57080000', 
        '57590000'
    ]
}

In [63]:
import os
import glob
import pandas as pd
from tqdm import tqdm

input_dir = "../outputs/pseudo-earl/"

search_pattern = os.path.join(input_dir, "**", "*radiomics.csv")
csv_files = glob.glob(search_pattern, recursive=True)

assert csv_files, "Aucun fichier CSV de radiomiques trouvé dans le répertoire spécifié."
    
print(f"📄 {len(csv_files)} fichiers trouvés. Début de la lecture...")

df_list = []
for file_path in tqdm(csv_files, desc="Lecture ..."):
    df = pd.read_csv(file_path)
    
    if df.empty: 
        continue
    
    parts = os.path.normpath(file_path).split(os.sep)
    
    # On vérifie qu'on a assez de profondeur (au moins 4 éléments : le fichier + 3 dossiers)
    if len(parts) >= 4:
        domain = parts[ -4 ]
        
        # Déduction de la Source et de la Target selon le nom du domaine
        if "_to_" in domain:
            domain_source, domain_target = domain.split("_to_", 1)
        else:
            domain_source = domain
            domain_target = ""
            
        # Insertion des métadonnées contextuelles au début du DataFrame
        df.insert(0, 'Domain_Target', domain_target)
        df.insert(0, 'Domain_Source', domain_source)
        df.insert(0, 'Domain', domain)
    else:
        df.insert(0, 'Source_Path', os.path.dirname(file_path))
    
    df_list.append(df)
        

assert df_list, "Aucun DataFrame valide n'a été créé à partir des fichiers CSV"

print("🔗 Concaténation des DataFrames...")
master_df = pd.concat(df_list, ignore_index=True)

print("\n" + "="*50)
print("✅ FUSION TERMINÉE AVEC SUCCÈS")
print("="*50)
print(f"Total des lignes  : {len(master_df)}")
print(f"Total des colonnes: {len(master_df.columns)}")
print("="*50)

master_df.head()

📄 513 fichiers trouvés. Début de la lecture...

Lecture ...: 100%|██████████| 513/513 [00:01<00:00, 361.77it/s]

🔗 Concaténation des DataFrames...

==================================================
✅ FUSION TERMINÉE AVEC SUCCÈS
==================================================
Total des lignes  : 1539
Total des colonnes: 101
==================================================

,Domain,Domain_Source,Domain_Target,Subject_ID,VOI,Modality,Image_Filename,ROI_type,original_firstorder_10Percentile,original_firstorder_90Percentile,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,nantes,nantes,,13250000,spleen,earl1,earl1.nii.gz,Original,1.108853,1.889848,...,9.150371,0.038310,0.009186,0.379496,0.000499,15.581725,0.000359,63.061096,0.002974,0.157052
1,nantes,nantes,,13250000,spleen,standard,pet.nii.gz,Original,1.066578,1.982609,...,5.920282,0.040870,0.017934,0.822880,0.000873,15.259549,0.000320,126.459328,0.004159,0.196147
2,nantes,nantes,,13250000,spleen,pseudo-earl1,pseudo-earl1.nii.gz,Original,1.108474,1.889222,...,9.103022,0.038391,0.009429,0.394996,0.000509,15.686371,0.000357,63.464036,0.002994,0.156125
3,nantes,nantes,,13250000,brain,earl1,earl1.nii.gz,Sphere_20.0mm,1.573257,7.224320,...,2.177729,0.026399,0.160444,55.308320,0.001404,0.492085,0.008649,422.314799,0.085733,5.148704
4,nantes,nantes,,13250000,brain,standard,pet.nii.gz,Sphere_20.0mm,1.422703,7.491142,...,1.458005,0.022190,0.201390,91.986378,0.001668,0.497140,0.006289,893.433076,0.118558,5.352433

In [58]:
import os
import numpy as np
import pandas as pd
import SimpleITK as sitk
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm import tqdm
import logging
import warnings

from skimage.metrics import structural_similarity as ssim
from scipy.stats import wilcoxon, spearmanr
from scipy.ndimage import distance_transform_edt

# Désactiver les warnings
sitk.ProcessObject.SetGlobalWarningDisplay(False)
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def generate_centered_sphere(sitk_mask, radius_mm=20.0, use_barycenter=False, margin_mm=1.0, shift_mm=(0.0, 0.0, 0.0)):
    spacing = sitk_mask.GetSpacing() 
    size = sitk_mask.GetSize()
    
    stats = sitk.LabelShapeStatisticsImageFilter()
    sitk_mask_uint8 = sitk.Cast(sitk_mask, sitk.sitkUInt8)
    stats.Execute(sitk_mask_uint8)
    
    if not stats.HasLabel(1):
        return None, "Masque vide"
        
    if use_barycenter:
        c_phys = list(stats.GetCentroid(1))
    else:
        mask_arr = sitk.GetArrayFromImage(sitk_mask_uint8)
        edt_map = distance_transform_edt(mask_arr, sampling=spacing[ ::-1 ])
        max_idx_flat = edt_map.argmax()
        cz, cy, cx = np.unravel_index(max_idx_flat, mask_arr.shape)
        c_phys = list(sitk_mask.TransformIndexToPhysicalPoint((int(cx), int(cy), int(cz))))

    c_phys[ 0 ] += shift_mm[ 0 ]
    c_phys[ 1 ] += shift_mm[ 1 ]
    c_phys[ 2 ] += shift_mm[ 2 ]
    
    c_idx = sitk_mask.TransformPhysicalPointToContinuousIndex(c_phys)
    
    nz, ny, nx = size[ 2 ], size[ 1 ], size[ 0 ]
    zz, yy, xx = np.ogrid[ :nz, :ny, :nx ]
    
    dist2 = (
        ((xx - c_idx[ 0 ]) * spacing[ 0 ])**2 + 
        ((yy - c_idx[ 1 ]) * spacing[ 1 ])**2 + 
        ((zz - c_idx[ 2 ]) * spacing[ 2 ])**2
    )
    
    sphere_arr = (dist2 <= radius_mm**2)
    safety_radius_sq = (radius_mm + margin_mm)**2
    safety_arr = (dist2 <= safety_radius_sq)

    if not np.any(sphere_arr):
        return None, "Sphère vide"

    mask_arr_bool = sitk.GetArrayFromImage(sitk_mask_uint8).astype(bool)

    if not np.all(mask_arr_bool[ safety_arr ]):
        return None, "Débordement"

    out_sitk = sitk.GetImageFromArray(sphere_arr.astype(np.uint8))
    out_sitk.CopyInformation(sitk_mask)
    return out_sitk, "Succès"

def calculate_metrics(gt_arr, pred_arr, mask_arr):
    voxels_gt = gt_arr[ mask_arr > 0 ]
    voxels_pred = pred_arr[ mask_arr > 0 ]
    
    if len(voxels_gt) == 0:
        return None
        
    # --- aRE ---
    voxels_gt_safe = np.where(voxels_gt == 0, 1e-8, voxels_gt)
    are_val = np.mean(np.abs((voxels_pred - voxels_gt_safe) / voxels_gt_safe)) * 100
    
    # --- PSNR ---
    mse = np.mean((voxels_gt - voxels_pred) ** 2)
    max_val = np.max(voxels_gt)
    psnr_val = 10 * np.log10((max_val ** 2) / mse) if mse > 1e-8 else np.inf
    
    # --- COV (Coefficient of Variation) ---
    mean_gt, mean_pred = np.mean(voxels_gt), np.mean(voxels_pred)
    cov_gt = (np.std(voxels_gt) / mean_gt) if mean_gt > 1e-8 else 0
    cov_pred = (np.std(voxels_pred) / mean_pred) if mean_pred > 1e-8 else 0
    
    # --- SSIM (3D) ---
    # Crop sur la Bounding Box du masque pour éviter l'influence massive du fond
    z, y, x = np.where(mask_arr > 0)
    z_min, z_max = np.min(z), np.max(z)
    y_min, y_max = np.min(y), np.max(y)
    x_min, x_max = np.min(x), np.max(x)
    
    gt_box = gt_arr[ z_min:z_max+1, y_min:y_max+1, x_min:x_max+1 ].copy()
    pred_box = pred_arr[ z_min:z_max+1, y_min:y_max+1, x_min:x_max+1 ].copy()
    mask_box = mask_arr[ z_min:z_max+1, y_min:y_max+1, x_min:x_max+1 ]
    
    # On met strictement à zéro ce qui est hors du masque dans la bounding box
    gt_box[ mask_box == 0 ] = 0
    pred_box[ mask_box == 0 ] = 0
    
    data_range = float(np.max(gt_box) - np.min(gt_box))
    win_size = min(7, min(gt_box.shape))
    if win_size % 2 == 0: 
        win_size -= 1
        
    if win_size >= 3:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            ssim_val = ssim(gt_box, pred_box, data_range=data_range, win_size=win_size)
    else:
        ssim_val = np.nan # La zone est trop petite pour calculer une texture SSIM
        
    return {
        "aRE": are_val,
        "PSNR": psnr_val,
        "SSIM": ssim_val,
        "COV_GT": cov_gt,
        "COV_Pred": cov_pred,
        "Mean_GT": mean_gt,
        "Mean_Pred": mean_pred
    }

def process_single_subject(args):
    subject_id, subject_path, gt_keyword, pred_keyword, mask_filename, sphere_vois, sphere_radius = args
    results_dict = {}
    
    if not os.path.isdir(subject_path):
        return subject_id, None, "Invalid path"
        
    # Les dossiers VOI sont situés directement dans le dossier du patient
    voi_folders = [f for f in os.listdir(subject_path) if os.path.isdir(os.path.join(subject_path, f))]
    
    for voi in voi_folders:
        voi_path = os.path.join(subject_path, voi)
        files = os.listdir(voi_path)
        
        gt_file = next((f for f in files if gt_keyword.lower() in f.lower() and f.endswith(('.nii', '.nii.gz'))), None)
        pred_file = next((f for f in files if pred_keyword.lower() in f.lower() and f.endswith(('.nii', '.nii.gz'))), None)
        
        if not gt_file or not pred_file or mask_filename not in files:
            continue
            
        try:
            gt_img = sitk.ReadImage(os.path.join(voi_path, gt_file))
            pred_img = sitk.ReadImage(os.path.join(voi_path, pred_file))
            mask_img = sitk.ReadImage(os.path.join(voi_path, mask_filename))
            
            # --- Condition Sphère vs Organe entier ---
            if voi in sphere_vois:
                sphere_img, msg = generate_centered_sphere(mask_img, radius_mm=sphere_radius)
                if sphere_img is not None:
                    mask_img = sphere_img
                else:
                    continue # La sphère est invalide (déborde ou vide), on ignore ce VOI
                    
            gt_arr = sitk.GetArrayFromImage(gt_img)
            pred_arr = sitk.GetArrayFromImage(pred_img)
            mask_arr = sitk.GetArrayFromImage(mask_img)
            
            metrics = calculate_metrics(gt_arr, pred_arr, mask_arr)
            if metrics:
                results_dict[ voi ] = metrics
                
        except Exception as e:
            pass # Poursuite silencieuse pour ne pas crasher le pool entier
            
    return subject_id, results_dict, "Success"


def evaluate(
    root_dir, include_only=None, sphere_vois=None, sphere_radius=20.0, 
    mask_filename="mask.nii.gz", gt_keyword="EARL", pred_keyword="predicted", num_workers=None
    ):
    if sphere_vois is None:
        sphere_vois = []
        
    if not os.path.exists(root_dir):
        logging.error(f"Le dossier {root_dir} n'existe pas.")
        return {}

    subjects = [s for s in os.listdir(root_dir) if os.path.isdir(os.path.join(root_dir, s))]
    if include_only:
        subjects = [s for s in subjects if s in include_only]
    
    tasks = [
        (subj, os.path.join(root_dir, subj), gt_keyword, pred_keyword, mask_filename, sphere_vois, sphere_radius) 
        for subj in subjects
    ]
    
    center_results = {}
    print(f"\n🚀 Lancement de l'évaluation sur : {os.path.basename(root_dir)} ({len(subjects)} patients)")
    print(f"🎯 Organes évalués par sphère ({sphere_radius}mm) : {sphere_vois}")
    
    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        futures = {executor.submit(process_single_subject, task): task for task in tasks}
        
        for future in tqdm(as_completed(futures), total=len(tasks), desc="Calcul des Métriques"):
            subject_id, subj_results, status = future.result()
            
            if subj_results:
                center_results[ subject_id ] = subj_results

    return center_results

def display_statistics(res):
    """
    Parcourt les résultats par patient, regroupe par VOI et affiche les statistiques + p-values.
    """
    # 1. Regrouper les résultats par VOI
    vois_trouvees = set()
    for subj in res.values():
        vois_trouvees.update(subj.keys())
        
    for voi in sorted(vois_trouvees):
        print("\n" + "="*60)
        print(f"📊 RÉSULTATS POUR LA VOI : {voi.upper()}")
        print("="*60)
        
        are_list, psnr_list, ssim_list = [], [], []
        cov_gt_list, cov_pred_list = [], []
        mean_gt_list, mean_pred_list = [], []
        
        for subj_id, subj_data in res.items():
            if voi in subj_data:
                m = subj_data[ voi ]
                if not np.isnan(m[ "aRE" ]): are_list.append(m[ "aRE" ])
                if not np.isnan(m[ "PSNR" ]) and m[ "PSNR" ] != np.inf: psnr_list.append(m[ "PSNR" ])
                if not np.isnan(m[ "SSIM" ]): ssim_list.append(m[ "SSIM" ])
                
                cov_gt_list.append(m[ "COV_GT" ])
                cov_pred_list.append(m[ "COV_Pred" ])
                mean_gt_list.append(m[ "Mean_GT" ])
                mean_pred_list.append(m[ "Mean_Pred" ])
        
        n = len(are_list)
        if n == 0:
            print("Aucune donnée valide pour ce calcul.")
            continue
            
        print(f"🔹 aRE  : {np.mean(are_list):.2f}% ± {np.std(are_list):.2f}%")
        print(f"🔹 PSNR : {np.mean(psnr_list):.2f} ± {np.std(psnr_list):.2f} dB")
        print(f"🔹 SSIM : {np.mean(ssim_list):.4f} ± {np.std(ssim_list):.4f}")
        print(f"🔹 COV  : GT = {np.mean(cov_gt_list):.3f} | Pred = {np.mean(cov_pred_list):.3f}")
        
        # --- Tests Statistiques ---
        try:
            _, p_mean = wilcoxon(mean_gt_list, mean_pred_list)
        except ValueError:
            p_mean = np.nan # Échoue si les arrays sont strictement identiques
            
        try:
            _, p_cov = wilcoxon(cov_gt_list, cov_pred_list)
        except ValueError:
            p_cov = np.nan
            
        corr, p_corr = spearmanr(mean_gt_list, mean_pred_list)
        
        print(f"\n🧪 Tests Statistiques (N = {n} patients valides)")
        print(f"  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = {p_mean:.4e}")
        print(f"  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = {p_cov:.4e}")
        print(f"  - Préservation du rang patient (Spearman ρ)         : ρ = {corr:.3f} (p = {p_corr:.4e})")

In [60]:
# Lancement des calculs
resultats = evaluate(
    root_dir='../outputs/pseudo-earl/nantes/',
    sphere_vois=['liver', 'lung', 'brain'],  # Celles-ci seront en sphère de 20mm
    mask_filename='mask.nii.gz',             # Les autres, comme 'spleen', utiliseront le masque entier
    gt_keyword='earl1', 
    pred_keyword='pseudo-earl1'
)

display_statistics(resultats)

🚀 Lancement de l'évaluation sur :  (89 patients)
🎯 Organes évalués par sphère (20.0mm) : ['liver', 'lung', 'brain']

Calcul des Métriques: 100%|██████████| 89/89 [00:24<00:00,  3.69it/s]

============================================================
📊 RÉSULTATS POUR LA VOI : BRAIN
============================================================
🔹 aRE  : 0.29% ± 0.06%
🔹 PSNR : 54.15 ± 1.44 dB
🔹 SSIM : 1.0000 ± 0.0000
🔹 COV  : GT = 0.539 | Pred = 0.540

🧪 Tests Statistiques (N = 89 patients valides)
  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = 4.2855e-01
  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = 1.2142e-02
  - Préservation du rang patient (Spearman ρ)         : ρ = 1.000 (p = 4.6947e-183)

============================================================
📊 RÉSULTATS POUR LA VOI : LESION
============================================================
🔹 aRE  : 0.43% ± 0.36%
🔹 PSNR : 50.60 ± 5.00 dB
🔹 SSIM : 1.0000 ± 0.0002
🔹 COV  : GT = 0.317 | Pred = 0.317

🧪 Tests Statistiques (N = 68 patients valides)
  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = 6.9558e-02
  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = 4.0230e-05
  - Préservation du rang patient (Spearman ρ)         : ρ = 1.000 (p = 6.3046e-112)

============================================================
📊 RÉSULTATS POUR LA VOI : LIVER
============================================================
🔹 aRE  : 0.23% ± 0.05%
🔹 PSNR : 50.90 ± 1.29 dB
🔹 SSIM : 0.9997 ± 0.0001
🔹 COV  : GT = 0.083 | Pred = 0.083

🧪 Tests Statistiques (N = 89 patients valides)
  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = 1.7196e-10
  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = 5.1140e-01
  - Préservation du rang patient (Spearman ρ)         : ρ = 1.000 (p = 4.6947e-183)

============================================================
📊 RÉSULTATS POUR LA VOI : LUNG
============================================================
🔹 aRE  : 0.47% ± 0.25%
🔹 PSNR : 49.78 ± 2.30 dB
🔹 SSIM : 0.9997 ± 0.0002
🔹 COV  : GT = 0.225 | Pred = 0.225

🧪 Tests Statistiques (N = 89 patients valides)
  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = 3.3229e-06
  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = 2.4232e-01
  - Préservation du rang patient (Spearman ρ)         : ρ = 1.000 (p = 3.3087e-149)

============================================================
📊 RÉSULTATS POUR LA VOI : SPLEEN
============================================================
🔹 aRE  : 0.25% ± 0.04%
🔹 PSNR : 53.29 ± 2.88 dB
🔹 SSIM : 0.9999 ± 0.0001
🔹 COV  : GT = 0.211 | Pred = 0.212

🧪 Tests Statistiques (N = 89 patients valides)
  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = 3.8316e-16
  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = 8.3034e-10
  - Préservation du rang patient (Spearman ρ)         : ρ = 1.000 (p = 0.0000e+00)

============================================================
📊 RÉSULTATS POUR LA VOI : URINARY_BLADDER
============================================================
🔹 aRE  : 0.40% ± 0.13%
🔹 PSNR : 57.14 ± 2.25 dB
🔹 SSIM : 1.0000 ± 0.0001
🔹 COV  : GT = 1.084 | Pred = 1.085

🧪 Tests Statistiques (N = 89 patients valides)
  - Biais d'Intensité (Wilcoxon sur moyennes GT/Pred) : p-value = 5.0827e-09
  - Biais de Variance (Wilcoxon sur COV GT/Pred)      : p-value = 1.4885e-03
  - Préservation du rang patient (Spearman ρ)         : ρ = 1.000 (p = 0.0000e+00)

### Radiomics evaluation

In [75]:
import numpy as np
import pandas as pd
from scipy.stats import norm, ttest_1samp
import warnings

# =============================================================================
# 1. FONCTIONS MATHÉMATIQUES (AVEC P-VALUES INTÉGRÉES)
# =============================================================================

def calculate_ccc_and_ci(y_true, y_pred, alpha=0.05):
    y_true = np.asarray(y_true, dtype=float).flatten()
    y_pred = np.asarray(y_pred, dtype=float).flatten()
    N = len(y_true)
    
    if N < 3: 
        return np.nan, np.nan, np.nan, np.nan
    
    if np.var(y_true) == 0 and np.var(y_pred) == 0:
        return 1.0, 1.0, 1.0, 0.0
        
    cor = np.corrcoef(y_true, y_pred)[ 0, 1 ]
    if np.isnan(cor): 
        return np.nan, np.nan, np.nan, np.nan
    
    mean_true, mean_pred = np.mean(y_true), np.mean(y_pred)
    var_true, var_pred = np.var(y_true), np.var(y_pred)
    sd_true, sd_pred = np.std(y_true), np.std(y_pred)
    
    numerator = 2 * cor * sd_true * sd_pred
    denominator = var_true + var_pred + (mean_true - mean_pred)**2
    ccc = numerator / denominator if denominator != 0 else np.nan
    
    if np.isnan(ccc):
        return np.nan, np.nan, np.nan, np.nan
    if ccc == 1.0:
        return 1.0, 1.0, 1.0, 0.0 

    # Transformée Z de Fisher pour calculer l'intervalle et la p-value (H0: CCC = 0)
    z = np.arctanh(ccc)
    se = 1.0 / np.sqrt(N - 2)
    z_critical = norm.ppf(1 - alpha / 2) 
    
    lower_ci = np.tanh(z - z_critical * se)
    upper_ci = np.tanh(z + z_critical * se)
    
    # Calcul de la p-value
    z_stat = z / se
    p_value = 2 * (1 - norm.cdf(np.abs(z_stat)))
    
    return ccc, lower_ci, upper_ci, p_value


def calculate_relative_bland_altman(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float).flatten()
    y_pred = np.asarray(y_pred, dtype=float).flatten()
    
    denominator = (y_true + y_pred) / 2.0
    safe_mask = denominator != 0
    
    if not np.any(safe_mask):
        return 0.0, 0.0, 0.0, 0.0, np.nan

    relative_diffs = (y_pred[ safe_mask ] - y_true[ safe_mask ]) / denominator[ safe_mask ]
    bias_relative = np.mean(relative_diffs)
    std_relative = np.std(relative_diffs, ddof=1) if len(relative_diffs) > 1 else 0

    loa_lower = bias_relative - (1.96 * std_relative)
    loa_upper = bias_relative + (1.96 * std_relative)
    
    # Test statistique (H0: Biais = 0)
    if len(relative_diffs) > 1 and std_relative > 0:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            _, p_value = ttest_1samp(relative_diffs, 0.0)
    else:
        p_value = np.nan
        
    return bias_relative, std_relative, loa_lower, loa_upper, p_value


# =============================================================================
# 2. ÉVALUATION PAR VOI DEPUIS LE MASTER DATAFRAME
# =============================================================================

def evaluate_radiomics_from_master(df, gt_mod='standard', pred_mod='harmonized'):
    df_gt = df[ df[ 'Modality' ] == gt_mod ].copy()
    df_pred = df[ df[ 'Modality' ] == pred_mod ].copy()
    
    merged = pd.merge(
        df_gt, df_pred, 
        on=[ 'Subject_ID', 'VOI', 'Domain_Source' ], 
        suffixes=('_gt', '_pred')
    )
    
    if merged.empty:
        print("⚠️ Aucune donnée appariée trouvée.")
        return None
        
    features = [c for c in df.columns if c.startswith('original_') and not c.startswith('original_shape_')]
    vois_list = merged[ 'VOI' ].unique()
    
    results_by_voi = {}
    
    for voi in vois_list:
        df_voi = merged[ merged[ 'VOI' ] == voi ]
        metrics_list = []
        
        for feat in features:
            gt_vals = df_voi[ f"{feat}_gt" ].dropna().values
            pred_vals = df_voi[ f"{feat}_pred" ].dropna().values
            
            if len(gt_vals) < 3:
                continue
                
            ccc, ccc_ci_low, ccc_ci_up, p_ccc = calculate_ccc_and_ci(gt_vals, pred_vals)
            bias, std_diff, loa_inf, loa_sup, p_bias = calculate_relative_bland_altman(gt_vals, pred_vals)
            
            family = feat.split('_')[ 1 ]
            
            metrics_list.append({
                'Feature': feat,
                'Family': family,
                'CCC': ccc,
                'CCC_95CI_Lower': ccc_ci_low,
                'CCC_95CI_Upper': ccc_ci_up,
                'p_val_CCC': p_ccc,
                'Bias_%': bias * 100,           
                'Bias_STD_%': std_diff * 100,    
                'LoA_Lower_%': loa_inf * 100,    
                'LoA_Upper_%': loa_sup * 100,
                'p_val_Bias': p_bias
            })
            
        if not metrics_list:
            continue
            
        df_metrics = pd.DataFrame(metrics_list).dropna(subset=[ 'CCC' ])
        
        # Résumé par famille
        family_summary = df_metrics.groupby('Family').agg({
            'CCC': 'mean',
            'CCC_95CI_Lower': 'mean',
            'CCC_95CI_Upper': 'mean',
            'p_val_CCC': lambda x: np.nanmedian(x) if not np.all(np.isnan(x)) else np.nan,
            'Bias_%': 'mean',
            'Bias_STD_%': 'mean',
            'LoA_Lower_%': 'mean',
            'LoA_Upper_%': 'mean',
            'p_val_Bias': lambda x: np.nanmedian(x) if not np.all(np.isnan(x)) else np.nan
        })
        
        # Formatage du tableau
        family_summary[ 'CCC [95% CI]' ] = family_summary.apply(
            lambda x: f"{x[ 'CCC' ]:.3f} [{x[ 'CCC_95CI_Lower' ]:.3f}, {x[ 'CCC_95CI_Upper' ]:.3f}]", axis=1
        )
        family_summary[ 'p-val (CCC)' ] = family_summary[ 'p_val_CCC' ].apply(
            lambda x: f"{x:.2e}" if not np.isnan(x) else "NaN"
        )
        family_summary[ 'Bias % [95% LoA]' ] = family_summary.apply(
            lambda x: f"{x[ 'Bias_%' ]:.2f}% [{x[ 'LoA_Lower_%' ]:.2f}, {x[ 'LoA_Upper_%' ]:.2f}]", axis=1
        )
        family_summary[ 'p-val (Bias)' ] = family_summary[ 'p_val_Bias' ].apply(
            lambda x: f"{x:.2e}" if not np.isnan(x) else "NaN"
        )
        
        # Résumé Global pour la VOI
        voi_global = {
            'N_Pairs': len(df_voi),
            'CCC_Mean': df_metrics[ 'CCC' ].mean(),
            'p_val_CCC_Median': df_metrics[ 'p_val_CCC' ].median(),
            'Bias_Mean': df_metrics[ 'Bias_%' ].mean(),
            'Bias_STD': df_metrics[ 'Bias_STD_%' ].mean(),
            'p_val_Bias_Median': df_metrics[ 'p_val_Bias' ].median(),
        }
        
        results_by_voi[ voi ] = {
            'df_details': df_metrics,
            'df_family': family_summary,
            'global': voi_global
        }
        
    return results_by_voi


# =============================================================================
# 3. AFFICHAGE (STYLE VOXEL-WISE + MOYENNE GLOBALE)
# =============================================================================

def display_radiomics_statistics(results_by_voi):
    if not results_by_voi:
        return
        
    grand_ccc = []
    grand_pval_ccc = []
    grand_bias = []
    grand_pval_bias = []
    
    # 1. Affichage boucle par VOI
    for voi in sorted(results_by_voi.keys()):
        data = results_by_voi[ voi ]
        g = data[ 'global' ]
        fam = data[ 'df_family' ]
        
        print("\n" + "="*60)
        print(f"📊 RÉSULTATS POUR LA VOI : {voi.upper()}")
        print("="*60)
        
        print(f"🔹 CCC Moyen Global   : {g[ 'CCC_Mean' ]:.4f}")
        print(f"🔹 Biais Relatif      : {g[ 'Bias_Mean' ]:.2f}% ± {g[ 'Bias_STD' ]:.2f}%")
        
        print(f"\n🧪 Tests Statistiques (N = {g[ 'N_Pairs' ]} patients valides)")
        print(f"  - Validation CCC (H0: CCC=0)       : p-value médiane = {g[ 'p_val_CCC_Median' ]:.4e}")
        print(f"  - Validation Biais (H0: Biais=0)   : p-value médiane = {g[ 'p_val_Bias_Median' ]:.4e}")
        
        print("\n  RÉSULTATS PAR FAMILLE :")
        cols_to_show = [ 'CCC [95% CI]', 'p-val (CCC)', 'Bias % [95% LoA]', 'p-val (Bias)' ]
        print(fam[ cols_to_show ].to_markdown())
        
        # Accumulation pour la moyenne finale
        grand_ccc.append(g[ 'CCC_Mean' ])
        grand_pval_ccc.append(g[ 'p_val_CCC_Median' ])
        grand_bias.append(g[ 'Bias_Mean' ])
        grand_pval_bias.append(g[ 'p_val_Bias_Median' ])

    # 2. Affichage Moyenne des Moyennes
    print("\n" + "="*80)
    print("🌐 MOYENNE DES MOYENNES (Toutes VOIs confondues)")
    print("="*80)
    print(f"🔹 CCC Global         : {np.nanmean(grand_ccc):.4f}")
    print(f"🔹 p-val CCC médiane  : {np.nanmedian(grand_pval_ccc):.4e}")
    print(f"🔹 Biais Relatif      : {np.nanmean(grand_bias):.2f}%")
    print(f"🔹 p-val Biais médiane: {np.nanmedian(grand_pval_bias):.4e}")
    print("="*80)

In [76]:
rad_results = evaluate_radiomics_from_master(
    master_df, 
    gt_mod='earl1',
    pred_mod='pseudo-earl1'    
)

display_radiomics_statistics(rad_results)

============================================================
📊 RÉSULTATS POUR LA VOI : BRAIN
============================================================
🔹 CCC Moyen Global   : 0.9989
🔹 Biais Relatif      : -0.05% ± 0.98%

🧪 Tests Statistiques (N = 89 patients valides)
  - Validation CCC (H0: CCC=0)       : p-value médiane = 0.0000e+00
  - Validation Biais (H0: Biais=0)   : p-value médiane = 7.9713e-02

  RÉSULTATS PAR FAMILLE :
| Family     | CCC [95% CI]         |   p-val (CCC) | Bias % [95% LoA]     |   p-val (Bias) |
|:-----------|:---------------------|--------------:|:---------------------|---------------:|
| firstorder | 1.000 [1.000, 1.000] |             0 | 0.01% [-0.38, 0.40]  |       0.132    |
| glcm       | 1.000 [1.000, 1.000] |             0 | 0.00% [-0.53, 0.54]  |       0.00106  |
| gldm       | 0.999 [0.998, 0.999] |             0 | -0.06% [-2.33, 2.21] |       0.142    |
| glrlm      | 1.000 [1.000, 1.000] |             0 | -0.03% [-0.77, 0.72] |       0.0518   |
| glszm      | 0.996 [0.994, 0.997] |             0 | -0.26% [-6.63, 6.10] |       0.344    |
| ngtdm      | 0.999 [0.999, 0.999] |             0 | 0.15% [-2.59, 2.88]  |       0.000841 |

============================================================
📊 RÉSULTATS POUR LA VOI : LESION
============================================================
🔹 CCC Moyen Global   : 0.9977
🔹 Biais Relatif      : 0.01% ± 7.09%

🧪 Tests Statistiques (N = 68 patients valides)
  - Validation CCC (H0: CCC=0)       : p-value médiane = 0.0000e+00
  - Validation Biais (H0: Biais=0)   : p-value médiane = 2.6315e-01

  RÉSULTATS PAR FAMILLE :
| Family     | CCC [95% CI]         |   p-val (CCC) | Bias % [95% LoA]       |   p-val (Bias) |
|:-----------|:---------------------|--------------:|:-----------------------|---------------:|
| firstorder | 1.000 [1.000, 1.000] |             0 | -0.09% [-4.23, 4.06]   |          0.253 |
| glcm       | 0.999 [0.999, 0.999] |             0 | 0.19% [-13.34, 13.72]  |          0.251 |
| gldm       | 0.996 [0.993, 0.997] |             0 | 0.07% [-20.32, 20.46]  |          0.441 |
| glrlm      | 0.996 [0.994, 0.998] |             0 | 0.21% [-11.01, 11.43]  |          0.111 |
| glszm      | 0.996 [0.994, 0.998] |             0 | -0.60% [-22.43, 21.24] |          0.395 |
| ngtdm      | 0.999 [0.999, 0.999] |             0 | 0.60% [-15.01, 16.21]  |          0.203 |

============================================================
📊 RÉSULTATS POUR LA VOI : LIVER
============================================================
🔹 CCC Moyen Global   : 0.9884
🔹 Biais Relatif      : 0.20% ± 3.48%

🧪 Tests Statistiques (N = 89 patients valides)
  - Validation CCC (H0: CCC=0)       : p-value médiane = 0.0000e+00
  - Validation Biais (H0: Biais=0)   : p-value médiane = 1.9912e-05

  RÉSULTATS PAR FAMILLE :
| Family     | CCC [95% CI]         |   p-val (CCC) | Bias % [95% LoA]      |   p-val (Bias) |
|:-----------|:---------------------|--------------:|:----------------------|---------------:|
| firstorder | 1.000 [1.000, 1.000] |             0 | -0.13% [-6.10, 5.83]  |       0.0151   |
| glcm       | 0.999 [0.998, 0.999] |             0 | 0.03% [-4.05, 4.11]   |       2.86e-15 |
| gldm       | 0.996 [0.993, 0.997] |             0 | 0.33% [-2.98, 3.64]   |       0.00201  |
| glrlm      | 0.999 [0.998, 0.999] |             0 | 0.03% [-1.32, 1.38]   |       1.18e-15 |
| glszm      | 0.940 [0.911, 0.960] |             0 | 0.88% [-21.37, 23.13] |       0.0617   |
| ngtdm      | 0.999 [0.999, 1.000] |             0 | 0.15% [-1.02, 1.31]   |       6.57e-19 |

============================================================
📊 RÉSULTATS POUR LA VOI : LUNG
============================================================
🔹 CCC Moyen Global   : 0.9863
🔹 Biais Relatif      : -0.16% ± 4.88%

🧪 Tests Statistiques (N = 89 patients valides)
  - Validation CCC (H0: CCC=0)       : p-value médiane = 0.0000e+00
  - Validation Biais (H0: Biais=0)   : p-value médiane = 2.2204e-01

  RÉSULTATS PAR FAMILLE :
| Family     | CCC [95% CI]         |   p-val (CCC) | Bias % [95% LoA]       |   p-val (Bias) |
|:-----------|:---------------------|--------------:|:-----------------------|---------------:|
| firstorder | 1.000 [1.000, 1.000] |             0 | -0.03% [-1.24, 1.18]   |        0.34    |
| glcm       | 1.000 [0.999, 1.000] |             0 | -0.01% [-2.50, 2.48]   |        0.0703  |
| gldm       | 0.996 [0.995, 0.998] |             0 | 0.03% [-4.44, 4.50]    |        0.155   |
| glrlm      | 0.999 [0.999, 1.000] |             0 | 0.16% [-1.89, 2.21]    |        0.00041 |
| glszm      | 0.925 [0.890, 0.950] |             0 | -1.12% [-42.31, 40.07] |        0.727   |
| ngtdm      | 0.999 [0.998, 0.999] |             0 | 0.26% [-10.39, 10.91]  |        0.368   |

============================================================
📊 RÉSULTATS POUR LA VOI : SPLEEN
============================================================
🔹 CCC Moyen Global   : 0.9979
🔹 Biais Relatif      : -0.04% ± 2.05%

🧪 Tests Statistiques (N = 89 patients valides)
  - Validation CCC (H0: CCC=0)       : p-value médiane = 0.0000e+00
  - Validation Biais (H0: Biais=0)   : p-value médiane = 3.2013e-03

  RÉSULTATS PAR FAMILLE :
| Family     | CCC [95% CI]         |   p-val (CCC) | Bias % [95% LoA]       |   p-val (Bias) |
|:-----------|:---------------------|--------------:|:-----------------------|---------------:|
| firstorder | 1.000 [1.000, 1.000] |             0 | -0.00% [-0.54, 0.54]   |       0.00074  |
| glcm       | 0.999 [0.999, 1.000] |             0 | 0.01% [-1.46, 1.48]    |       3.02e-12 |
| gldm       | 0.997 [0.995, 0.998] |             0 | -0.02% [-4.68, 4.65]   |       0.0105   |
| glrlm      | 0.998 [0.997, 0.999] |             0 | -0.10% [-4.12, 3.92]   |       1.35e-05 |
| glszm      | 0.994 [0.991, 0.996] |             0 | -0.14% [-10.31, 10.02] |       0.28     |
| ngtdm      | 0.999 [0.999, 1.000] |             0 | 0.10% [-7.07, 7.28]    |       0.308    |

============================================================
📊 RÉSULTATS POUR LA VOI : URINARY_BLADDER
============================================================
🔹 CCC Moyen Global   : 0.9987
🔹 Biais Relatif      : -0.17% ± 1.55%

🧪 Tests Statistiques (N = 89 patients valides)
  - Validation CCC (H0: CCC=0)       : p-value médiane = 0.0000e+00
  - Validation Biais (H0: Biais=0)   : p-value médiane = 1.4970e-01

  RÉSULTATS PAR FAMILLE :
| Family     | CCC [95% CI]         |   p-val (CCC) | Bias % [95% LoA]     |   p-val (Bias) |
|:-----------|:---------------------|--------------:|:---------------------|---------------:|
| firstorder | 1.000 [1.000, 1.000] |             0 | -0.04% [-0.57, 0.49] |       0.022    |
| glcm       | 1.000 [0.999, 1.000] |             0 | -0.08% [-0.81, 0.64] |       0.0447   |
| gldm       | 0.998 [0.997, 0.999] |             0 | -0.35% [-5.87, 5.16] |       0.274    |
| glrlm      | 0.998 [0.998, 0.999] |             0 | -0.34% [-4.54, 3.86] |       0.000821 |
| glszm      | 0.996 [0.995, 0.998] |             0 | -0.19% [-5.77, 5.39] |       0.45     |
| ngtdm      | 1.000 [1.000, 1.000] |             0 | 0.03% [-4.33, 4.39]  |       0.518    |

================================================================================
🌐 MOYENNE DES MOYENNES (Toutes VOIs confondues)
================================================================================
🔹 CCC Global         : 0.9947
🔹 p-val CCC médiane  : 0.0000e+00
🔹 Biais Relatif      : -0.03%
🔹 p-val Biais médiane: 1.1471e-01
================================================================================

### Calcul aRE sur les différentes VOIs

In [25]:
import os
import numpy as np
import SimpleITK as sitk
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm import tqdm
import logging

# Désactiver les warnings SimpleITK pour ne pas casser la barre tqdm
sitk.ProcessObject.SetGlobalWarningDisplay(False)
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def calculate_voxelwise_are(gt_arr, pred_arr, mask_arr):
    # voxels_gt = gt_arr[mask_arr > 0]
    # voxels_pred = pred_arr[mask_arr > 0]
    
    # if len(voxels_gt) == 0:
    #     return np.nan # Masque vide
        
    # # Sécurité : éviter la division par zéro sur le bruit de fond
    # voxels_gt_safe = np.where(voxels_gt == 0, 1e-8, voxels_gt)
    
    # # Calcul de l'aRE par voxel, puis moyenne globale
    # are_array = np.abs((voxels_pred - voxels_gt_safe) / voxels_gt_safe)
    # return np.mean(are_array) * 100
    voxels_gt = gt_arr[ mask_arr > 0 ]
    voxels_pred = pred_arr[ mask_arr > 0 ]
    
    if len(voxels_gt) == 0:
        return np.nan
        
    # --- aRE ---
    voxels_gt_safe = np.where(voxels_gt == 0, 1e-8, voxels_gt)
    are_val = np.mean(np.abs((voxels_pred - voxels_gt_safe) / voxels_gt_safe)) * 100
    return are_val

def process_single_subject(args):
    subject_id, subject_path, gt_keyword, pred_keyword, mask_list = args
    
    # 1. Recherche des fichiers
    files = os.listdir(subject_path)
    gt_file = next((f for f in files if gt_keyword.lower() in f.lower() and f.endswith(('.nii', '.nii.gz'))), None)
    pred_file = next((f for f in files if pred_keyword.lower() in f.lower() and f.endswith(('.nii', '.nii.gz'))), None)
    
    if not gt_file or not pred_file:
        return subject_id, None, f"Fichiers PET manquants (GT ou Pred)"

    results_dict = {}
    
    try:
        # 2. Chargement des volumes TEP (une seule fois par patient)
        gt_img = sitk.ReadImage(os.path.join(subject_path, gt_file))
        pred_img = sitk.ReadImage(os.path.join(subject_path, pred_file))
        
        gt_arr = sitk.GetArrayFromImage(gt_img)
        pred_arr = sitk.GetArrayFromImage(pred_img)
        
        # 3. Boucle sur la liste des masques demandés
        for mask_name in mask_list:
            mask_path = os.path.join(subject_path, mask_name)
            
            if not os.path.exists(mask_path):
                results_dict[mask_name] = np.nan
                continue
                
            # Lecture du masque et calcul
            mask_img = sitk.ReadImage(mask_path)
            mask_arr = sitk.GetArrayFromImage(mask_img)
            
            are_value = calculate_voxelwise_are(gt_arr, pred_arr, mask_arr)
            results_dict[mask_name] = are_value
            
        return subject_id, results_dict, "Success"

    except Exception as e:
        return subject_id, None, str(e)


def evaluate(dir, include_only, mask_list, gt_keyword="EARL", pred_keyword="predicted", num_workers=None):
    """
    Parcourt un centre, lance le calcul en parallèle et renvoie un dictionnaire.
    """
    if not os.path.exists(dir):
        logging.error(f"Le dossier {dir} n'existe pas.")
        return {}

    # Lister uniquement les sous-dossiers (les sujets)
    subjects = [s for s in os.listdir(dir) if os.path.isdir(os.path.join(dir, s)) and s in include_only]
    
    # Préparation des arguments pour le multiprocessing
    tasks = [
        (subj, os.path.join(dir, subj), gt_keyword, pred_keyword, mask_list) 
        for subj in subjects
    ]
    
    center_results = {}
    failed_subjects = []

    # Utilisation de ProcessPoolExecutor (idéal pour le CPU-bound / calcul Numpy)
    print(f"\n🚀 Lancement de l'évaluation sur le centre : {os.path.basename(dir)} ({len(subjects)} patients)")
    
    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        futures = {executor.submit(process_single_subject, task): task for task in tasks}
        
        for future in tqdm(as_completed(futures), total=len(tasks), desc="Calcul aRE"):
            subject_id, subj_results, status = future.result()
            
            if subj_results is not None:
                center_results[subject_id] = subj_results
            else:
                failed_subjects.append((subject_id, status))
                
    if failed_subjects:
        logging.warning(f"{len(failed_subjects)} sujets ont échoué sur ce centre (ex: {failed_subjects}).")

    return center_results


def display_aRE(res, masks):
    # display mean by organ over the whole dataset
    for mask in masks:
        values = [res[subject][mask] for subject in res if mask in res[subject] and not np.isnan(res[subject][mask])]
        if values:
            mean_value = np.mean(values)
            print(f"Mean aRE for {mask}: {mean_value:.2f}% +- {np.std(values):.2f}%")
        else:
            print(f"No valid aRE values found for {mask}.")

### Calcul Biais Bland-Altman

In [28]:
import os
import pandas as pd
import numpy as np
from scipy.stats import norm
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm import tqdm
import logging

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def calculate_ccc_and_ci(y_true, y_pred, alpha=0.05):
    y_true = np.asarray(y_true, dtype=float).flatten()
    y_pred = np.asarray(y_pred, dtype=float).flatten()
    N = len(y_true)
    
    if N < 3: return np.nan, np.nan, np.nan
    
    if np.var(y_true) == 0 and np.var(y_pred) == 0:
        return 1.0, 1.0, 1.0
        
    # CORRECTION : [1] est vital pour obtenir un scalaire et non un array numpy
    cor = np.corrcoef(y_true, y_pred)[0, 1]
    
    if np.isnan(cor): return np.nan, np.nan, np.nan
    
    mean_true, mean_pred = np.mean(y_true), np.mean(y_pred)
    var_true, var_pred = np.var(y_true), np.var(y_pred)
    sd_true, sd_pred = np.std(y_true), np.std(y_pred)
    
    numerator = 2 * cor * sd_true * sd_pred
    denominator = var_true + var_pred + (mean_true - mean_pred)**2
    ccc = numerator / denominator if denominator != 0 else np.nan
    
    if np.isnan(ccc) or ccc == 1.0:
        return ccc, ccc, ccc 

    z = np.arctanh(ccc)
    se = 1.0 / np.sqrt(N - 2)
    z_critical = norm.ppf(1 - alpha/2) 
    
    lower_ci = np.tanh(z - z_critical * se)
    upper_ci = np.tanh(z + z_critical * se)
    
    return ccc, lower_ci, upper_ci

def calculate_relative_bland_altman( y_true, y_pred ):
    y_true = np.asarray( y_true, dtype=float ).flatten()
    y_pred = np.asarray( y_pred, dtype=float ).flatten()
    
    denominator = (y_true + y_pred) / 2.0
    safe_mask = denominator != 0
    
    if not np.any( safe_mask ):
        return 0.0, 0.0, 0.0, 0.0

    relative_diffs = (y_pred[safe_mask] - y_true[safe_mask]) / denominator[safe_mask]
    bias_relative = np.mean(relative_diffs)
    
    std_relative = np.std( relative_diffs, ddof=1 ) if len( relative_diffs ) > 1 else 0

    loa_lower = bias_relative - ( 1.96 * std_relative )
    loa_upper = bias_relative + ( 1.96 * std_relative )
    
    return bias_relative, std_relative, loa_lower, loa_upper


def process_single_csv(args):
    subject_id, csv_path, gt_mod, pred_mod = args
    try:
        if not os.path.exists(csv_path):
            return subject_id, None, "CSV introuvable"

        df = pd.read_csv(csv_path)
        df_gt = df[df['Image_Filename'] == gt_mod]
        df_pred = df[df['Image_Filename'] == pred_mod]

        if df_gt.empty or df_pred.empty:
            return subject_id, None, f"Modalité manquante"

        feature_cols = [c for c in df.columns if c.startswith('original_')]

        gt_vals = df_gt[feature_cols].to_dict('records')[0]
        pred_vals = df_pred[feature_cols].to_dict('records')[0]

        return subject_id, {'GT': gt_vals, 'Pred': pred_vals}, "Success"

    except Exception as e:
        return subject_id, None, str(e)


def evaluate_radiomics_center(
    center_dir, 
    include_only=None,
    csv_name="liver_radiomics.csv", 
    gt_mod="PET_EARL", 
    pred_mod="PET_Predicted_DSR10", 
    num_workers=4
    ):    
    if not os.path.exists(center_dir):
        logging.error(f"Le dossier {center_dir} n'existe pas.")
        return None

    subjects = [s for s in os.listdir(center_dir) if os.path.isdir(os.path.join(center_dir, s))]
    if include_only is not None:
        subjects = [s for s in subjects if s in include_only]
    
    tasks = [
        (subj, os.path.join(center_dir, subj, csv_name), gt_mod, pred_mod)
        for subj in subjects
    ]

    extracted_data = []
    print(f"\n📊 Extraction Radiomiques : {os.path.basename(center_dir)} ({len(subjects)} patients)")
    
    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        futures = {executor.submit(process_single_csv, task): task for task in tasks}

        for future in tqdm(as_completed(futures), total=len(tasks), desc="Lecture CSV"):
            subj_id, data, status = future.result()
            if data is not None:
                extracted_data.append(data)
            else:
                logging.debug(f"[{subj_id}] Ignoré : {status}")

    if not extracted_data:
        logging.warning(f"Aucune donnée valide trouvée pour {center_dir}.")
        return None
    
    features = extracted_data[0]['GT'].keys()
    metrics_per_feature = {}

    for feat in features:
        # Comme on a extrait des dictionnaires plats plus haut, l'accès direct par [feat] marche parfaitement
        gt_array = [subj_data['GT'][feat] for subj_data in extracted_data]
        pred_array = [subj_data['Pred'][feat] for subj_data in extracted_data]

        ccc, ccc_ci_low, ccc_ci_up = calculate_ccc_and_ci(gt_array, pred_array)
        bias, std_diff, loa_inf, loa_sup = calculate_relative_bland_altman(gt_array, pred_array)

        parts = feat.split('_')
        family = parts[1] if len(parts) > 1 else 'unknown'

        metrics_per_feature[feat] = {
            'family': family,
            'CCC': ccc,
            'CCC_95CI_Lower': ccc_ci_low,
            'CCC_95CI_Upper': ccc_ci_up,
            'Bias_%': bias * 100,           # Passage en %
            'Bias_STD_%': std_diff * 100,    # Passage en %
            'LoA_Lower_%': loa_inf * 100,    # Passage en %
            'LoA_Upper_%': loa_sup * 100     # Passage en %
        }

    df_metrics = pd.DataFrame.from_dict(metrics_per_feature, orient='index')
    df_clean = df_metrics.dropna() 

    # Création des colonnes formatées (Scientific Notation)
    df_clean[ 'CCC [95% CI]' ] = df_clean.apply(
        lambda x: f"{x[ 'CCC' ]:.3f} [{x[ 'CCC_95CI_Lower' ]:.3f}, {x[ 'CCC_95CI_Upper' ]:.3f}]", axis=1)
    df_clean[ 'Bias % [95% LoA]' ] = df_clean.apply(
        lambda x: f"{x[ 'Bias_%' ]:.2f}% [{x[ 'LoA_Lower_%' ]:.2f}, {x[ 'LoA_Upper_%' ]:.2f}]", axis=1)

    family_summary = df_clean.groupby('family').agg({
        'CCC': 'mean',
        'CCC_95CI_Lower': 'mean',
        'CCC_95CI_Upper': 'mean',
        'Bias_%': 'mean',
        'Bias_STD_%': 'mean',
        'LoA_Lower_%': 'mean',
        'LoA_Upper_%': 'mean'
    })

    # Formatage scientifique pour le résumé par famille
    family_summary[ 'CCC [95% CI]' ] = family_summary.apply(
        lambda x: f"{x[ 'CCC' ]:.3f} [{x[ 'CCC_95CI_Lower' ]:.3f}, {x[ 'CCC_95CI_Upper' ]:.3f}]", axis=1)
    family_summary[ 'Bias % [95% LoA]' ] = family_summary.apply(
        lambda x: f"{x[ 'Bias_%' ]:.2f}% [{x[ 'LoA_Lower_%' ]:.2f}, {x[ 'LoA_Upper_%' ]:.2f}]", axis=1)
    

    global_summary = {
        'CCC_Global': df_clean[ 'CCC' ].mean(),
        'CCC_CI_Lower_Global': df_clean['CCC_95CI_Lower'].mean(), # Ajoute cette ligne
        'CCC_CI_Upper_Global': df_clean['CCC_95CI_Upper'].mean(),
        'Bias_Global_%': df_clean[ 'Bias_%' ].mean(),
        'Bias_STD_Global_%': df_clean[ 'Bias_STD_%' ].mean()
    }

    return {
        'df_details': df_metrics,
        'df_family': family_summary,
        'dict_global': global_summary,
        'raw_data': extracted_data
    }
    
# def display_radiomics_results(results):
#     print(" RÉSULTATS PAR FAMILLE DE RADIOMIQUES ".center(100))
#     print("="*100)
    
#     # On définit les colonnes qu'on veut afficher (format scientifique)
#     cols_to_show = [ 'CCC [95% CI]', 'Bias % [95% LoA]', 'Bias_STD_%' ]
    
#     # Affichage du tableau de famille
#     print(results[ 'df_family' ][ cols_to_show ].to_markdown())

#     print("\n" + "="*100)
#     print(" SCORES GLOBAUX (Toutes familles) ".center(100))
#     print("="*100)
    
#     # Mise à jour des clés avec le suffixe _% et _Global
#     print(f"CCC Moyen Global     : {results[ 'dict_global' ][ 'CCC_Global' ]:.4f}")
#     print(f"Biais Relatif Moyen  : {results[ 'dict_global' ][ 'Bias_Global_%' ]:.2f}% ± {results[ 'dict_global' ][ 'Bias_STD_Global_%' ]:.2f}%")
    
    # Sauvegarde du fichier détaillé complet
    # output_csv = f"{os.path.basename(center_path)}_metrics_detailed.csv"
    # results[ 'df_details' ].to_csv(output_csv) # Sauvegarde réelle
    # print(f"\n✅ Détails complets sauvegardés dans : {output_csv}")
    
def display_radiomics_results(results):
    print(" RÉSULTATS PAR FAMILLE DE RADIOMIQUES ".center(100))
    print("="*100)
    
    # Colonnes à afficher dans le tableau (format scientifique déjà géré dans evaluate)
    cols_to_show = [ 'CCC [95% CI]', 'Bias % [95% LoA]', 'Bias_STD_%' ]
    print(results[ 'df_family' ][ cols_to_show ].to_markdown())

    print("\n" + "="*100)
    print(" SCORES GLOBAUX (Toutes familles) ".center(100))
    print("="*100)
    
    # Extraction des données depuis le dictionnaire dict_global
    dg = results['dict_global']
    
    ccc_mean = dg['CCC_Global']
    ccc_low  = dg['CCC_CI_Lower_Global']  # Nouvelle clé
    ccc_high = dg['CCC_CI_Upper_Global'] # Nouvelle clé
    
    bias_mean = dg['Bias_Global_%']
    bias_std  = dg['Bias_STD_Global_%']

    # Affichage formaté : CCC moyen [Bas, Haut]
    print(f"CCC Moyen Global     : {ccc_mean:.4f} [{ccc_low:.4f}, {ccc_high:.4f}]")
    print(f"Biais Relatif Moyen  : {bias_mean:.2f}% ± {bias_std:.2f}%")

# EARL 1

In [29]:
# Remplace par le chemin de ton centre
center_path = 'data/PET-EARL/foundation-dataset/domain_a100/'

vois = [
    'liver_radiomics.csv', 'brain_radiomics.csv', 'bladder_radiomics.csv',
    'lung_radiomics.csv', 'spleen_radiomics.csv', 'lesion_radiomics.csv'
]

for voi in vois:
    results = evaluate_radiomics_center(
        center_dir=center_path,
        include_only=evaluation_subject_ids['domain_a100'],
        csv_name=voi,  
        gt_mod='EARL_TEP_TAP_EARL1.nii.gz',                      
        pred_mod='predicted_EARL1_DSR10.nii.gz',         
        num_workers=50                           
    )

    if results:
        print(f"\n📊 Résultats pour {voi} : ---------------")
        display_radiomics_results(results)

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 1196.21it/s]

📊 Résultats pour liver_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 0.998 [0.996, 0.999] | 0.43% [-7.21, 8.08]   |      3.9005  |
| glcm       | 0.978 [0.961, 0.987] | 1.23% [-8.61, 11.06]  |      5.01683 |
| gldm       | 0.925 [0.877, 0.956] | 0.11% [-18.98, 19.20] |      9.73827 |
| glrlm      | 0.948 [0.913, 0.969] | 0.16% [-16.26, 16.57] |      8.37678 |
| glszm      | 0.753 [0.617, 0.847] | 1.54% [-63.62, 66.70] |     33.245   |
| ngtdm      | 0.929 [0.880, 0.959] | 0.21% [-24.74, 25.16] |     12.7288  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9272 [0.8833, 0.9560]
Biais Relatif Moyen  : 0.72% ± 11.36%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 714.86it/s]

📊 Résultats pour brain_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.02% [-1.13, 1.10]  |     0.567359 |
| glcm       | 0.998 [0.996, 0.999] | 0.04% [-1.52, 1.60]   |     0.796134 |
| gldm       | 0.991 [0.984, 0.995] | 0.28% [-7.89, 8.45]   |     4.16692  |
| glrlm      | 0.997 [0.994, 0.998] | 0.21% [-5.58, 5.99]   |     2.94917  |
| glszm      | 0.995 [0.992, 0.997] | 0.01% [-12.39, 12.41] |     6.32553  |
| ngtdm      | 0.998 [0.996, 0.999] | 0.23% [-6.36, 6.81]   |     3.36176  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9965 [0.9940, 0.9980]
Biais Relatif Moyen  : 0.10% ± 2.72%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 730.11it/s]

📊 Résultats pour bladder_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.14% [-2.91, 2.63]  |      1.41278 |
| glcm       | 1.000 [0.999, 1.000] | -0.48% [-6.16, 5.20]  |      2.89654 |
| gldm       | 0.993 [0.988, 0.996] | -1.04% [-10.71, 8.63] |      4.93209 |
| glrlm      | 0.999 [0.997, 0.999] | -0.49% [-7.28, 6.30]  |      3.46398 |
| glszm      | 0.992 [0.986, 0.995] | -0.88% [-10.53, 8.77] |      4.92364 |
| ngtdm      | 1.000 [1.000, 1.000] | 0.27% [-3.32, 3.86]   |      1.83286 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9973 [0.9952, 0.9984]
Biais Relatif Moyen  : -0.53% ± 3.30%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 788.28it/s]

📊 Résultats pour lung_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.10% [-2.25, 2.44]   |      1.19611 |
| glcm       | 0.995 [0.992, 0.997] | 3.33% [-40.51, 47.17] |     22.3693  |
| gldm       | 0.985 [0.974, 0.991] | 0.22% [-14.80, 15.24] |      7.66319 |
| glrlm      | 0.988 [0.979, 0.993] | 0.33% [-12.73, 13.40] |      6.66624 |
| glszm      | 0.911 [0.859, 0.946] | 2.86% [-53.76, 59.47] |     28.8855  |
| ngtdm      | 0.827 [0.752, 0.886] | 1.55% [-49.13, 52.23] |     25.8584  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9698 [0.9528, 0.9814]
Biais Relatif Moyen  : 1.54% ± 14.66%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 1215.35it/s]

📊 Résultats pour spleen_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.16% [-2.18, 2.49]    |     1.19305  |
| glcm       | 0.999 [0.998, 0.999] | 0.09% [-1.26, 1.43]    |     0.688351 |
| gldm       | 0.999 [0.998, 0.999] | -0.26% [-2.63, 2.12]   |     1.20998  |
| glrlm      | 0.999 [0.999, 1.000] | -0.17% [-1.63, 1.28]   |     0.741813 |
| glszm      | 0.984 [0.972, 0.991] | -0.94% [-18.88, 16.99] |     9.14995  |
| ngtdm      | 0.998 [0.996, 0.999] | 0.13% [-9.85, 10.11]   |     5.09352  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9965 [0.9939, 0.9980]
Biais Relatif Moyen  : -0.17% ± 2.57%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 740.60it/s]

📊 Résultats pour lesion_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.998 [0.997, 0.999] | 1.90% [-65.21, 69.02]  |     34.2435  |
| glcm       | 0.990 [0.982, 0.995] | 3.14% [-22.67, 28.96]  |     13.1699  |
| gldm       | 0.990 [0.982, 0.995] | -0.99% [-24.36, 22.39] |     11.9254  |
| glrlm      | 0.996 [0.993, 0.998] | 0.01% [-11.76, 11.78]  |      6.00403 |
| glszm      | 0.989 [0.980, 0.994] | -2.05% [-34.35, 30.25] |     16.478   |
| ngtdm      | 0.978 [0.958, 0.988] | 2.08% [-22.67, 26.84]  |     12.6317  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9920 [0.9850, 0.9958]
Biais Relatif Moyen  : 0.79% ± 16.37%

In [30]:
# Remplace par le chemin de ton centre
center_path = 'data/PET-EARL/foundation-dataset/domain_chb/'

for voi in vois:
    results = evaluate_radiomics_center(
        center_dir=center_path,
        include_only=evaluation_subject_ids['domain_chb'],
        csv_name=voi,  
        gt_mod='EARL_TEPTAPRECONEARL_Ano.nii.gz',                      
        pred_mod='predicted_EARL1_DSR10.nii.gz',       
        num_workers=50                           
    )

    if results:
        print(f"\n📊 Résultats pour {voi} : ---------------")
        display_radiomics_results(results)

📊 Extraction Radiomiques :  (100 patients)

Lecture CSV: 100%|██████████| 100/100 [00:00<00:00, 1225.61it/s]

📊 Résultats pour liver_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.10% [-1.68, 1.88]    |     0.907944 |
| glcm       | 0.991 [0.987, 0.994] | -0.04% [-4.82, 4.74]   |     2.43836  |
| gldm       | 0.984 [0.977, 0.989] | -0.13% [-11.71, 11.44] |     5.90665  |
| glrlm      | 0.986 [0.979, 0.990] | -0.03% [-10.21, 10.16] |     5.19634  |
| glszm      | 0.924 [0.892, 0.948] | -0.79% [-28.61, 27.04] |    14.1963   |
| ngtdm      | 0.978 [0.968, 0.985] | 0.13% [-17.15, 17.41]  |     8.81864  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9787 [0.9692, 0.9854]
Biais Relatif Moyen  : -0.15% ± 5.50%

📊 Extraction Radiomiques :  (100 patients)

Lecture CSV: 100%|██████████| 100/100 [00:00<00:00, 1663.22it/s]

📊 Résultats pour brain_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [0.999, 1.000] | -0.48% [-11.74, 10.79] |      5.74848 |
| glcm       | 0.998 [0.997, 0.998] | 0.28% [-4.77, 5.32]    |      2.57299 |
| gldm       | 0.990 [0.986, 0.993] | -0.09% [-10.95, 10.76] |      5.53755 |
| glrlm      | 0.996 [0.993, 0.997] | -0.17% [-7.61, 7.27]   |      3.79758 |
| glszm      | 0.982 [0.974, 0.988] | -0.17% [-16.23, 15.89] |      8.19272 |
| ngtdm      | 0.996 [0.994, 0.997] | 0.13% [-8.79, 9.05]    |      4.55162 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9938 [0.9909, 0.9958]
Biais Relatif Moyen  : -0.09% ± 4.92%

📊 Extraction Radiomiques :  (100 patients)

Lecture CSV: 100%|██████████| 100/100 [00:00<00:00, 1060.51it/s]

📊 Résultats pour bladder_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]     |   Bias_STD_% |
|:-----------|:---------------------|:---------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.03% [-1.14, 1.08] |     0.567398 |
| glcm       | 1.000 [1.000, 1.000] | -0.04% [-0.88, 0.80] |     0.427113 |
| gldm       | 0.998 [0.997, 0.999] | 0.10% [-6.46, 6.65]  |     3.34369  |
| glrlm      | 0.999 [0.998, 0.999] | 0.08% [-4.75, 4.91]  |     2.46232  |
| glszm      | 0.999 [0.999, 1.000] | 0.15% [-7.78, 8.07]  |     4.04277  |
| ngtdm      | 1.000 [1.000, 1.000] | 0.01% [-2.95, 2.96]  |     1.50861  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9993 [0.9990, 0.9995]
Biais Relatif Moyen  : 0.04% ± 1.92%

📊 Extraction Radiomiques :  (100 patients)

Lecture CSV: 100%|██████████| 100/100 [00:00<00:00, 1689.77it/s]

📊 Résultats pour lung_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.08% [-0.66, 0.82]    |     0.377498 |
| glcm       | 1.000 [1.000, 1.000] | -0.23% [-5.53, 5.08]   |     2.70775  |
| gldm       | 0.997 [0.995, 0.998] | -0.29% [-3.52, 2.93]   |     1.6451   |
| glrlm      | 1.000 [1.000, 1.000] | -0.04% [-1.41, 1.32]   |     0.696461 |
| glszm      | 0.911 [0.869, 0.940] | -1.64% [-46.81, 43.53] |    23.0452   |
| ngtdm      | 0.817 [0.773, 0.859] | -0.42% [-10.08, 9.24]  |     4.92799  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9742 [0.9644, 0.9818]
Biais Relatif Moyen  : -0.40% ± 5.37%

📊 Extraction Radiomiques :  (100 patients)

Lecture CSV: 100%|██████████| 100/100 [00:00<00:00, 1104.00it/s]

📊 Résultats pour spleen_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.05% [-0.87, 0.77]  |     0.418465 |
| glcm       | 0.999 [0.998, 0.999] | -0.05% [-1.66, 1.57]  |     0.822939 |
| gldm       | 0.998 [0.997, 0.999] | -0.10% [-6.37, 6.18]  |     3.20066  |
| glrlm      | 0.997 [0.996, 0.998] | -0.10% [-4.95, 4.75]  |     2.47404  |
| glszm      | 0.990 [0.986, 0.993] | 0.12% [-12.42, 12.66] |     6.39942  |
| ngtdm      | 0.995 [0.993, 0.997] | -0.03% [-8.80, 8.73]  |     4.47261  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9971 [0.9956, 0.9980]
Biais Relatif Moyen  : -0.03% ± 2.54%

📊 Extraction Radiomiques :  (100 patients)

Lecture CSV: 100%|██████████| 100/100 [00:00<00:00, 1603.59it/s]

📊 Résultats pour lesion_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.999 [0.999, 0.999] | 0.33% [-8.47, 9.14]    |      4.49453 |
| glcm       | 0.997 [0.996, 0.998] | -0.79% [-14.13, 12.56] |      6.80888 |
| gldm       | 0.971 [0.956, 0.981] | -0.34% [-21.62, 20.95] |     10.8579  |
| glrlm      | 0.986 [0.978, 0.991] | -0.19% [-14.36, 13.97] |      7.22725 |
| glszm      | 0.972 [0.958, 0.982] | -0.10% [-23.06, 22.86] |     11.7139  |
| ngtdm      | 0.996 [0.995, 0.998] | -0.35% [-21.05, 20.36] |     10.5644  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9873 [0.9808, 0.9916]
Biais Relatif Moyen  : -0.26% ± 8.09%

In [31]:
# Remplace par le chemin de ton centre
center_path = 'data/PET-EARL/foundation-dataset/domain_rennes/'

for voi in vois:
    results = evaluate_radiomics_center(
        center_dir=center_path,
        include_only=evaluation_subject_ids['domain_rennes'],
        csv_name=voi,  
        gt_mod='EARL_TEP_TAP_EARL.nii.gz',                      
        pred_mod='predicted_EARL1_DSR10.nii.gz',       
        num_workers=50                           
    )

    if results:
        print(f"\n📊 Résultats pour {voi} : ---------------")
        display_radiomics_results(results)

📊 Extraction Radiomiques :  (75 patients)

Lecture CSV: 100%|██████████| 75/75 [00:00<00:00, 1222.45it/s]

📊 Résultats pour liver_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.992 [0.987, 0.995] | -2.16% [-22.06, 17.74] |     10.153   |
| glcm       | 0.964 [0.944, 0.977] | -2.77% [-23.21, 17.67] |     10.4281  |
| gldm       | 0.928 [0.891, 0.953] | -0.21% [-18.60, 18.17] |      9.38045 |
| glrlm      | 0.945 [0.917, 0.965] | 0.19% [-15.64, 16.02]  |      8.07589 |
| glszm      | 0.787 [0.693, 0.856] | 0.82% [-40.30, 41.95]  |     20.9803  |
| ngtdm      | 0.915 [0.872, 0.945] | -1.71% [-30.53, 27.11] |     14.7034  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9276 [0.8927, 0.9521]
Biais Relatif Moyen  : -1.08% ± 11.86%

📊 Extraction Radiomiques :  (75 patients)

Lecture CSV: 100%|██████████| 75/75 [00:00<00:00, 1042.01it/s]

📊 Résultats pour brain_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [0.999, 1.000] | 0.02% [-1.34, 1.37]   |     0.691812 |
| glcm       | 0.997 [0.996, 0.998] | 0.08% [-2.06, 2.23]   |     1.09456  |
| gldm       | 0.989 [0.983, 0.993] | 0.47% [-9.69, 10.63]  |     5.18509  |
| glrlm      | 0.994 [0.991, 0.996] | 0.33% [-7.02, 7.68]   |     3.74936  |
| glszm      | 0.954 [0.937, 0.968] | 0.48% [-16.41, 17.37] |     8.61781  |
| ngtdm      | 0.996 [0.994, 0.998] | 0.16% [-8.31, 8.64]   |     4.32417  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9886 [0.9837, 0.9922]
Biais Relatif Moyen  : 0.24% ± 3.56%

📊 Extraction Radiomiques :  (75 patients)

Lecture CSV: 100%|██████████| 75/75 [00:00<00:00, 1211.08it/s]

📊 Résultats pour bladder_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.999 [0.999, 1.000] | -0.18% [-5.29, 4.94]   |      2.60799 |
| glcm       | 0.999 [0.999, 1.000] | -1.75% [-38.37, 34.87] |     18.6831  |
| gldm       | 0.998 [0.997, 0.999] | -0.04% [-11.10, 11.02] |      5.64388 |
| glrlm      | 0.999 [0.998, 0.999] | -0.19% [-8.72, 8.34]   |      4.35345 |
| glszm      | 0.989 [0.983, 0.993] | -0.28% [-13.70, 13.13] |      6.84524 |
| ngtdm      | 0.997 [0.995, 0.998] | 0.09% [-8.68, 8.85]    |      4.47181 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9971 [0.9955, 0.9982]
Biais Relatif Moyen  : -0.57% ± 8.34%

📊 Extraction Radiomiques :  (75 patients)

Lecture CSV: 100%|██████████| 75/75 [00:00<00:00, 1107.51it/s]

📊 Résultats pour lung_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.998 [0.996, 0.999] | -0.05% [-4.87, 4.78]   |      2.4626  |
| glcm       | 0.991 [0.986, 0.995] | -0.32% [-10.87, 10.23] |      5.38185 |
| gldm       | 0.975 [0.961, 0.984] | 0.17% [-15.87, 16.21]  |      8.18306 |
| glrlm      | 0.985 [0.977, 0.991] | -0.07% [-12.87, 12.73] |      6.53119 |
| glszm      | 0.825 [0.753, 0.880] | 0.62% [-61.44, 62.67]  |     31.6623  |
| ngtdm      | 0.948 [0.920, 0.967] | -0.32% [-27.57, 26.93] |     13.9035  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9581 [0.9390, 0.9718]
Biais Relatif Moyen  : 0.01% ± 10.42%

📊 Extraction Radiomiques :  (75 patients)

Lecture CSV: 100%|██████████| 75/75 [00:00<00:00, 931.53it/s]

📊 Résultats pour spleen_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.999 [0.998, 0.999] | 0.24% [-5.03, 5.52]    |      2.68973 |
| glcm       | 0.992 [0.987, 0.995] | 1.12% [-21.06, 23.31]  |     11.3186  |
| gldm       | 0.982 [0.972, 0.989] | -0.06% [-12.40, 12.29] |      6.29979 |
| glrlm      | 0.973 [0.959, 0.983] | 0.29% [-10.92, 11.49]  |      5.71572 |
| glszm      | 0.941 [0.912, 0.962] | 0.77% [-23.06, 24.60]  |     12.157   |
| ngtdm      | 0.993 [0.989, 0.996] | -0.67% [-18.18, 16.84] |      8.9353  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9800 [0.9694, 0.9871]
Biais Relatif Moyen  : 0.47% ± 7.95%

📊 Extraction Radiomiques :  (75 patients)

Lecture CSV: 100%|██████████| 75/75 [00:00<00:00, 1404.21it/s]

📊 Résultats pour lesion_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.994 [0.991, 0.996] | -0.82% [-25.95, 24.30] |      12.82   |
| glcm       | 0.955 [0.927, 0.972] | 3.13% [-69.04, 75.30]  |      36.8215 |
| gldm       | 0.959 [0.935, 0.974] | 1.15% [-43.28, 45.58]  |      22.6677 |
| glrlm      | 0.949 [0.919, 0.968] | 0.73% [-26.04, 27.51]  |      13.6608 |
| glszm      | 0.959 [0.935, 0.975] | 2.16% [-46.23, 50.54]  |      24.6841 |
| ngtdm      | 0.715 [0.625, 0.794] | 1.56% [-58.55, 61.67]  |      30.6676 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9499 [0.9244, 0.9674]
Biais Relatif Moyen  : 1.40% ± 23.64%

# EARL 2

In [33]:
# Remplace par le chemin de ton centre
center_path = 'data/PET-EARL/foundation-dataset/domain_a100/'

for voi in vois:
    results = evaluate_radiomics_center(
        center_dir=center_path,
        include_only=evaluation_subject_ids['domain_a100'],
        csv_name=voi,  
        gt_mod='EARL_TEP_TAP_EARL2.nii.gz',                      
        pred_mod='predicted_EARL2_DSR10.nii.gz',       
        num_workers=50                           
    )

    if results:
        print(f"\n📊 Résultats pour {voi} : ---------------")
        display_radiomics_results(results)

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 660.02it/s]

📊 Résultats pour liver_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.994 [0.989, 0.996] | -0.02% [-6.07, 6.04]   |      3.09096 |
| glcm       | 0.979 [0.964, 0.988] | -0.27% [-8.66, 8.13]   |      4.28354 |
| gldm       | 0.950 [0.916, 0.971] | -0.00% [-14.26, 14.25] |      7.27272 |
| glrlm      | 0.954 [0.923, 0.973] | 0.16% [-11.59, 11.92]  |      5.99623 |
| glszm      | 0.870 [0.789, 0.922] | 0.07% [-27.02, 27.16]  |     13.8206  |
| ngtdm      | 0.942 [0.901, 0.966] | -0.39% [-17.71, 16.94] |      8.83927 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9525 [0.9209, 0.9720]
Biais Relatif Moyen  : -0.05% ± 6.68%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 816.23it/s]

📊 Résultats pour brain_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.16% [-1.19, 1.51]   |     0.690008 |
| glcm       | 0.998 [0.996, 0.999] | 0.17% [-3.29, 3.63]   |     1.76586  |
| gldm       | 0.980 [0.966, 0.988] | 0.34% [-12.38, 13.06] |     6.49071  |
| glrlm      | 0.990 [0.983, 0.994] | 0.21% [-9.71, 10.14]  |     5.0631   |
| glszm      | 0.967 [0.948, 0.980] | 0.20% [-15.54, 15.94] |     8.0307   |
| ngtdm      | 0.997 [0.994, 0.998] | 0.28% [-6.57, 7.14]   |     3.4995   |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9888 [0.9815, 0.9934]
Biais Relatif Moyen  : 0.21% ± 4.01%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 995.28it/s]

📊 Résultats pour bladder_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.02% [-2.04, 2.00]  |     1.03251  |
| glcm       | 1.000 [0.999, 1.000] | 0.10% [-1.85, 2.04]   |     0.991454 |
| gldm       | 0.998 [0.997, 0.999] | 0.37% [-7.00, 7.74]   |     3.76045  |
| glrlm      | 0.999 [0.998, 0.999] | 0.25% [-4.37, 4.86]   |     2.35427  |
| glszm      | 0.993 [0.988, 0.996] | 0.17% [-11.49, 11.84] |     5.95179  |
| ngtdm      | 1.000 [0.999, 1.000] | 0.02% [-3.85, 3.88]   |     1.97217  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9981 [0.9967, 0.9989]
Biais Relatif Moyen  : 0.15% ± 2.56%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 785.83it/s]

📊 Résultats pour lung_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 0.999 [0.999, 1.000] | 0.22% [-3.12, 3.56]   |      1.70357 |
| glcm       | 0.997 [0.995, 0.998] | -0.01% [-6.82, 6.80]  |      3.47533 |
| gldm       | 0.976 [0.959, 0.986] | 0.27% [-16.73, 17.26] |      8.67178 |
| glrlm      | 0.986 [0.975, 0.992] | 0.07% [-13.47, 13.61] |      6.90871 |
| glszm      | 0.841 [0.762, 0.899] | 0.84% [-55.40, 57.09] |     28.696   |
| ngtdm      | 0.987 [0.978, 0.993] | 0.80% [-23.56, 25.16] |     12.4277  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9650 [0.9457, 0.9782]
Biais Relatif Moyen  : 0.28% ± 9.33%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 799.38it/s]

📊 Résultats pour spleen_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]      |   Bias_STD_% |
|:-----------|:---------------------|:----------------------|-------------:|
| firstorder | 1.000 [0.999, 1.000] | 0.12% [-1.94, 2.18]   |      1.05098 |
| glcm       | 0.997 [0.995, 0.998] | 0.10% [-2.00, 2.21]   |      1.07226 |
| gldm       | 0.997 [0.994, 0.998] | 0.03% [-3.52, 3.58]   |      1.81175 |
| glrlm      | 0.998 [0.996, 0.999] | 0.28% [-2.29, 2.85]   |      1.31104 |
| glszm      | 0.972 [0.952, 0.984] | 0.38% [-15.54, 16.30] |      8.1219  |
| ngtdm      | 0.997 [0.995, 0.998] | 0.05% [-8.99, 9.09]   |      4.61057 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9934 [0.9886, 0.9962]
Biais Relatif Moyen  : 0.17% ± 2.62%

📊 Extraction Radiomiques :  (50 patients)

Lecture CSV: 100%|██████████| 50/50 [00:00<00:00, 1032.17it/s]

📊 Résultats pour lesion_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 0.999 [0.998, 0.999] | 0.28% [-6.52, 7.08]    |      3.46796 |
| glcm       | 0.996 [0.992, 0.998] | 0.29% [-18.52, 19.09]  |      9.59652 |
| gldm       | 0.982 [0.967, 0.991] | -0.61% [-27.35, 26.12] |     13.6402  |
| glrlm      | 0.993 [0.987, 0.996] | 0.19% [-12.09, 12.47]  |      6.26642 |
| glszm      | 0.968 [0.943, 0.983] | -1.21% [-36.90, 34.47] |     18.2051  |
| ngtdm      | 0.996 [0.992, 0.998] | 0.84% [-25.94, 27.62]  |     13.6638  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9890 [0.9799, 0.9941]
Biais Relatif Moyen  : -0.10% ± 10.15%

In [32]:
# Remplace par le chemin de ton centre
center_path = 'data/Nantes_dataset_Nifti/'

for voi in vois:
    results = evaluate_radiomics_center(
        center_dir=center_path,
        include_only=evaluation_subject_ids['domain_nantes'],
        csv_name=voi,  
        gt_mod='EARL2_PET_EARL2.nii.gz',                      
        pred_mod='predicted_EARL2_DSR10.nii.gz',       
        num_workers=50                           
    )

    if results:
        print(f"\n📊 Résultats pour {voi} : ---------------")
        display_radiomics_results(results)

📊 Extraction Radiomiques :  (88 patients)

Lecture CSV: 100%|██████████| 88/88 [00:00<00:00, 1297.55it/s]

📊 Résultats pour liver_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.24% [-3.36, 3.83]    |      1.83558 |
| glcm       | 0.990 [0.985, 0.994] | 0.07% [-5.29, 5.44]    |      2.73766 |
| gldm       | 0.970 [0.955, 0.980] | 0.32% [-12.81, 13.44]  |      6.69639 |
| glrlm      | 0.979 [0.968, 0.986] | -0.04% [-11.00, 10.92] |      5.59355 |
| glszm      | 0.938 [0.908, 0.958] | 1.16% [-25.26, 27.57]  |     13.4774  |
| ngtdm      | 0.987 [0.981, 0.992] | 0.14% [-14.27, 14.55]  |      7.35252 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9779 [0.9670, 0.9853]
Biais Relatif Moyen  : 0.31% ± 5.75%

📊 Extraction Radiomiques :  (88 patients)

Lecture CSV: 100%|██████████| 88/88 [00:00<00:00, 1048.85it/s]

📊 Résultats pour brain_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]     |   Bias_STD_% |
|:-----------|:---------------------|:---------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | 0.01% [-0.39, 0.42]  |     0.204631 |
| glcm       | 1.000 [0.999, 1.000] | 0.03% [-0.76, 0.81]  |     0.400476 |
| gldm       | 0.996 [0.994, 0.998] | -0.25% [-5.82, 5.32] |     2.84192  |
| glrlm      | 0.998 [0.998, 0.999] | -0.23% [-4.28, 3.82] |     2.06551  |
| glszm      | 0.995 [0.993, 0.997] | -0.27% [-8.27, 7.74] |     4.0846   |
| ngtdm      | 0.999 [0.998, 0.999] | 0.18% [-3.03, 3.38]  |     1.63439  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9982 [0.9972, 0.9988]
Biais Relatif Moyen  : -0.10% ± 1.72%

📊 Extraction Radiomiques :  (88 patients)

Lecture CSV: 100%|██████████| 88/88 [00:00<00:00, 1498.65it/s]

📊 Résultats pour bladder_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]     |   Bias_STD_% |
|:-----------|:---------------------|:---------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.02% [-0.63, 0.58] |     0.309584 |
| glcm       | 0.999 [0.999, 1.000] | -0.08% [-0.79, 0.62] |     0.357564 |
| gldm       | 0.998 [0.997, 0.999] | -0.31% [-5.49, 4.88] |     2.64532  |
| glrlm      | 0.999 [0.998, 0.999] | -0.23% [-3.94, 3.47] |     1.89206  |
| glszm      | 0.999 [0.999, 1.000] | -0.21% [-5.47, 5.06] |     2.68652  |
| ngtdm      | 1.000 [1.000, 1.000] | 0.17% [-4.09, 4.43]  |     2.17427  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9993 [0.9989, 0.9995]
Biais Relatif Moyen  : -0.14% ± 1.46%

📊 Extraction Radiomiques :  (88 patients)

Lecture CSV: 100%|██████████| 88/88 [00:00<00:00, 1130.69it/s]

📊 Résultats pour lung_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.01% [-1.21, 1.19]   |      0.61001 |
| glcm       | 0.999 [0.999, 1.000] | 0.05% [-2.67, 2.77]    |      1.38785 |
| gldm       | 0.997 [0.995, 0.998] | -0.03% [-4.74, 4.68]   |      2.40449 |
| glrlm      | 0.999 [0.999, 1.000] | 0.15% [-2.10, 2.40]    |      1.14924 |
| glszm      | 0.913 [0.873, 0.941] | -1.85% [-47.30, 43.61] |     23.19    |
| ngtdm      | 0.999 [0.998, 0.999] | 0.32% [-10.53, 11.17]  |      5.53383 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9842 [0.9768, 0.9894]
Biais Relatif Moyen  : -0.27% ± 5.32%

📊 Extraction Radiomiques :  (88 patients)

Lecture CSV: 100%|██████████| 88/88 [00:00<00:00, 1106.57it/s]

📊 Résultats pour spleen_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]     |   Bias_STD_% |
|:-----------|:---------------------|:---------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.01% [-0.61, 0.58] |     0.303436 |
| glcm       | 1.000 [1.000, 1.000] | 0.01% [-0.56, 0.58]  |     0.289418 |
| gldm       | 0.999 [0.999, 1.000] | 0.04% [-1.27, 1.35]  |     0.666651 |
| glrlm      | 1.000 [1.000, 1.000] | -0.07% [-0.69, 0.55] |     0.317705 |
| glszm      | 0.995 [0.992, 0.996] | -0.14% [-8.49, 8.21] |     4.26141  |
| ngtdm      | 1.000 [1.000, 1.000] | 0.08% [-4.00, 4.17]  |     2.08626  |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9989 [0.9983, 0.9992]
Biais Relatif Moyen  : -0.03% ± 1.13%

📊 Extraction Radiomiques :  (88 patients)

Lecture CSV: 100%|██████████| 88/88 [00:00<00:00, 1102.86it/s]

📊 Résultats pour lesion_radiomics.csv : ---------------
                                RÉSULTATS PAR FAMILLE DE RADIOMIQUES
====================================================================================================
| family     | CCC [95% CI]         | Bias % [95% LoA]       |   Bias_STD_% |
|:-----------|:---------------------|:-----------------------|-------------:|
| firstorder | 1.000 [1.000, 1.000] | -0.12% [-6.18, 5.94]   |      3.0924  |
| glcm       | 0.998 [0.997, 0.999] | 0.16% [-14.34, 14.66]  |      7.39642 |
| gldm       | 0.996 [0.993, 0.997] | -0.37% [-19.03, 18.30] |      9.52264 |
| glrlm      | 0.998 [0.996, 0.999] | -0.18% [-9.66, 9.30]   |      4.83583 |
| glszm      | 0.995 [0.991, 0.997] | -1.03% [-22.78, 20.73] |     11.0988  |
| ngtdm      | 0.999 [0.998, 0.999] | 0.58% [-14.63, 15.79]  |      7.75913 |

====================================================================================================
                                  SCORES GLOBAUX (Toutes familles)
====================================================================================================
CCC Moyen Global     : 0.9974 [0.9959, 0.9984]
Biais Relatif Moyen  : -0.21% ± 7.14%

/tmp/ipykernel_2289675/3649739442.py:158: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[ 'CCC [95% CI]' ] = df_clean.apply(
/tmp/ipykernel_2289675/3649739442.py:160: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[ 'Bias % [95% LoA]' ] = df_clean.apply(

## PSNR - SSIM

In [1]:
import os
import torch
import SimpleITK as sitk
import numpy as np
import logging
import pandas as pd
from tqdm import tqdm
from torchmetrics.image import PeakSignalNoiseRatio, StructuralSimilarityIndexMeasure

# Configuration du logging pour le notebook
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def evaluate_psnr_ssim(dir_path, include_only, gt_filename, pred_filename, mask_filename):
    if not os.path.exists(dir_path):
        logging.error(f"Le dossier {dir_path} n'existe pas.")
        return None

    # 1. Lister les patients
    all_subjects = [ s for s in os.listdir(dir_path) if os.path.isdir(os.path.join(dir_path, s)) ]
    
    if include_only is not None and len(include_only) > 0:
        subjects = [ s for s in all_subjects if s in include_only ]
    else:
        subjects = all_subjects
        
    if not subjects:
        logging.warning("Aucun sujet à traiter.")
        return None
    
    center_results = {}
    failed_subjects = []

    logging.info(f"🚀 Évaluation Séquentielle PSNR/SSIM : {os.path.basename(dir_path)} ({len(subjects)} patients)")
    logging.info(f"Masque utilisé : {mask_filename} | Plafond SUV : 25.0")

    # 2. Boucle Séquentielle (plus de multiprocessing)
    for subj_id in tqdm(subjects, desc="Calcul PSNR/SSIM", position=0, leave=True):
        subj_dir = os.path.join(dir_path, subj_id)
        
        try:
            # Formatage des noms
            gt_name = gt_filename if gt_filename.endswith((".nii", ".nii.gz")) else f"{gt_filename}.nii.gz"
            pred_name = pred_filename if pred_filename.endswith((".nii", ".nii.gz")) else f"{pred_filename}.nii.gz"
            mask_name = mask_filename if mask_filename.endswith((".nii", ".nii.gz")) else f"{mask_filename}.nii.gz"

            gt_path = os.path.join(subj_dir, gt_name)
            pred_path = os.path.join(subj_dir, pred_name)
            mask_path = os.path.join(subj_dir, mask_name)

            # Vérification de l'existence des 3 fichiers
            if not os.path.exists(gt_path): raise FileNotFoundError(f"GT manquant : {gt_name}")
            if not os.path.exists(pred_path): raise FileNotFoundError(f"Pred manquant : {pred_name}")
            if not os.path.exists(mask_path): raise FileNotFoundError(f"Masque manquant : {mask_name}")

            # Chargement SimpleITK -> Numpy
            gt_arr = sitk.GetArrayFromImage(sitk.ReadImage(gt_path))
            pred_arr = sitk.GetArrayFromImage(sitk.ReadImage(pred_path))
            mask_arr = sitk.GetArrayFromImage(sitk.ReadImage(mask_path))

            if not (gt_arr.shape == pred_arr.shape == mask_arr.shape):
                raise ValueError(f"Tailles incohérentes. GT:{gt_arr.shape}, Pred:{pred_arr.shape}, Mask:{mask_arr.shape}")

            # Conversion en Tenseurs PyTorch
            gt_tensor = torch.from_numpy(gt_arr).unsqueeze(0).unsqueeze(0).float()
            pred_tensor = torch.from_numpy(pred_arr).unsqueeze(0).unsqueeze(0).float()
            mask_tensor = torch.from_numpy(mask_arr).unsqueeze(0).unsqueeze(0).float()
            
            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            gt_tensor = gt_tensor.to(device)
            pred_tensor = pred_tensor.to(device)
            mask_tensor = mask_tensor.to(device)

            # --- APPLICATION DU MASQUE ET GESTION CLINIQUE ---
            CLINICAL_SUV_MAX = 25.0
            
            # Plafonnement (Clamping)
            gt_tensor = torch.clamp(gt_tensor, min=0.0, max=CLINICAL_SUV_MAX)
            pred_tensor = torch.clamp(pred_tensor, min=0.0, max=CLINICAL_SUV_MAX)

            # Binarisation du masque (au cas où il ne serait pas 0/1) et application
            binary_mask = mask_tensor > 0
            gt_tensor = gt_tensor * binary_mask.float()
            pred_tensor = pred_tensor * binary_mask.float()

            # Évaluation
            psnr_metric = PeakSignalNoiseRatio(data_range=CLINICAL_SUV_MAX).to(device)
            ssim_metric = StructuralSimilarityIndexMeasure(data_range=CLINICAL_SUV_MAX, return_full_image=False).to(device)

            psnr_val = psnr_metric(pred_tensor, gt_tensor).item()
            ssim_val = ssim_metric(pred_tensor, gt_tensor).item()

            # Sauvegarde des résultats pour ce patient
            center_results[ subj_id ] = {
                'PSNR': psnr_val,
                'SSIM': ssim_val
            }

        except Exception as e:
            failed_subjects.append((subj_id, str(e)))

    # 3. Bilan
    if failed_subjects:
        logging.warning(f"⚠️ {len(failed_subjects)} patients ont échoué.")
        for fail in failed_subjects[ :3 ]: # Affiche les 3 premières erreurs pour debug
            logging.warning(f"   -> [{fail[ 0 ]}] : {fail[ 1 ]}")

    if center_results:
        df_results = pd.DataFrame.from_dict(center_results, orient='index')
        df_results.index.name = 'Subject_ID'
        return df_results
    
    return None

In [6]:
results_df = evaluate_psnr_ssim(
    dir_path='data/Nantes_dataset_Nifti/',
    include_only=evaluation_subject_ids['domain_nantes'],
    gt_filename='EARL2_PET_EARL2',
    pred_filename='predicted_EARL2_DSR10',
    mask_filename='body.nii.gz'
)

# --- AFFICHAGE ET SAUVEGARDE ---
if results_df is not None:
    print("\n" + "="*50)
    print(" RÉSUMÉ DES MÉTRIQUES ".center(50))
    print("="*50)
    
    mean_psnr = results_df[ 'PSNR' ].mean()
    std_psnr = results_df[ 'PSNR' ].std()
    mean_ssim = results_df[ 'SSIM' ].mean()
    std_ssim = results_df[ 'SSIM' ].std()
    
    print(f"PSNR Moyen : {mean_psnr:.2f} ± {std_psnr:.2f} dB")
    print(f"SSIM Moyen : {mean_ssim:.4f} ± {std_ssim:.4f}")
    
    display(results_df.head())

==================================================
               RÉSUMÉ DES MÉTRIQUES
==================================================
PSNR Moyen : 79.49 ± 2.10 dB
SSIM Moyen : 1.0000 ± 0.0000

                 PSNR      SSIM
Subject_ID
15080000    79.221077  0.999996
13250000    81.058777  0.999996
24200000    82.207848  0.999998
18500000    81.088631  0.999996
30200000    79.588486  0.999995

In [7]:
results_df = evaluate_psnr_ssim(
    dir_path='data/PET-EARL/foundation-dataset/domain_chb/',
    include_only=evaluation_subject_ids['domain_chb'],
    gt_filename='EARL_TEPTAPRECONEARL_Ano',
    pred_filename='predicted_EARL1_DSR10',
    mask_filename='body.nii.gz'
)

# --- AFFICHAGE ET SAUVEGARDE ---
if results_df is not None:
    print("\n" + "="*50)
    print(" RÉSUMÉ DES MÉTRIQUES ".center(50))
    print("="*50)
    
    mean_psnr = results_df[ 'PSNR' ].mean()
    std_psnr = results_df[ 'PSNR' ].std()
    mean_ssim = results_df[ 'SSIM' ].mean()
    std_ssim = results_df[ 'SSIM' ].std()
    
    print(f"PSNR Moyen : {mean_psnr:.2f} ± {std_psnr:.2f} dB")
    print(f"SSIM Moyen : {mean_ssim:.4f} ± {std_ssim:.4f}")
    
    display(results_df.head())

INFO: 🚀 Évaluation Séquentielle PSNR/SSIM :  (100 patients)
INFO: Masque utilisé : body.nii.gz | Plafond SUV : 25.0
Calcul PSNR/SSIM: 100%|██████████| 100/100 [43:55<00:00, 26.36s/it]

==================================================
               RÉSUMÉ DES MÉTRIQUES
==================================================
PSNR Moyen : 80.24 ± 3.04 dB
SSIM Moyen : 1.0000 ± 0.0000

                  PSNR      SSIM
Subject_ID
9401154473m  82.302299  0.999997
9401185783m  79.957306  0.999992
9401154314m  82.279701  0.999996
9401165833m  79.680786  0.999992
9401183962m  79.739761  0.999995

In [8]:
results_df = evaluate_psnr_ssim(
    dir_path='data/PET-EARL/foundation-dataset/domain_a100/',
    include_only=evaluation_subject_ids['domain_a100'],
    gt_filename='EARL_TEP_TAP_EARL1',
    pred_filename='predicted_EARL1_DSR10',
    mask_filename='body.nii.gz'
)

# --- AFFICHAGE ET SAUVEGARDE ---
if results_df is not None:
    print("\n" + "="*50)
    print(" RÉSUMÉ DES MÉTRIQUES ".center(50))
    print("="*50)
    
    mean_psnr = results_df[ 'PSNR' ].mean()
    std_psnr = results_df[ 'PSNR' ].std()
    mean_ssim = results_df[ 'SSIM' ].mean()
    std_ssim = results_df[ 'SSIM' ].std()
    
    print(f"PSNR Moyen : {mean_psnr:.2f} ± {std_psnr:.2f} dB")
    print(f"SSIM Moyen : {mean_ssim:.4f} ± {std_ssim:.4f}")
    
    display(results_df.head())

INFO: 🚀 Évaluation Séquentielle PSNR/SSIM :  (50 patients)
INFO: Masque utilisé : body.nii.gz | Plafond SUV : 25.0
Calcul PSNR/SSIM: 100%|██████████| 50/50 [25:01<00:00, 30.03s/it]

==================================================
               RÉSUMÉ DES MÉTRIQUES
==================================================
PSNR Moyen : 74.42 ± 1.97 dB
SSIM Moyen : 1.0000 ± 0.0000

                 PSNR      SSIM
Subject_ID
A100765582  74.940582  0.999977
A100678049  72.132797  0.999987
A100751077  77.545891  0.999991
A100786953  76.252701  0.999988
A100750063  75.889954  0.999989

In [9]:
results_df = evaluate_psnr_ssim(
    dir_path='data/PET-EARL/foundation-dataset/domain_rennes/',
    include_only=evaluation_subject_ids['domain_rennes'],
    gt_filename='EARL_TEP_TAP_EARL',
    pred_filename='predicted_EARL1_DSR10',
    mask_filename='body.nii.gz'
)

# --- AFFICHAGE ET SAUVEGARDE ---
if results_df is not None:
    print("\n" + "="*50)
    print(" RÉSUMÉ DES MÉTRIQUES ".center(50))
    print("="*50)
    
    mean_psnr = results_df[ 'PSNR' ].mean()
    std_psnr = results_df[ 'PSNR' ].std()
    mean_ssim = results_df[ 'SSIM' ].mean()
    std_ssim = results_df[ 'SSIM' ].std()
    
    print(f"PSNR Moyen : {mean_psnr:.2f} ± {std_psnr:.2f} dB")
    print(f"SSIM Moyen : {mean_ssim:.4f} ± {std_ssim:.4f}")
    
    display(results_df.head())

INFO: 🚀 Évaluation Séquentielle PSNR/SSIM :  (75 patients)
INFO: Masque utilisé : body.nii.gz | Plafond SUV : 25.0
Calcul PSNR/SSIM: 100%|██████████| 75/75 [47:33<00:00, 38.04s/it]

==================================================
               RÉSUMÉ DES MÉTRIQUES
==================================================
PSNR Moyen : 68.07 ± 1.92 dB
SSIM Moyen : 0.9999 ± 0.0001

                             PSNR      SSIM
Subject_ID
HNxD4294tCwor8Q279PadP  68.112289  0.999915
2ybL92aNCnoQcHxamqh4r8  69.156540  0.999925
QCUUZfRhj7hnniiVkAXs6B  68.654648  0.999906
6fqzQDyXnAxwWmt7Cg3Yom  69.629440  0.999942
Jssbv8wnaAUMY9BAzkzFLr  68.879852  0.999917